---
- name: "Create outline user"
  ansible.builtin.user:
    name: "outline"
    home: "/var/www/outline"
    move_home: true
    system: true
    shell: "/sbin/nologin"
    password: "!"

- name: "Create outline directory"
  ansible.builtin.file:
    path: "{{ outline_project_source }}"
    state: "directory"
    owner: "outline"
    group: "outline"

- name: "Do database setup"
  become_user: "postgres"
  become: true
  block:
  - name: "Ensure Postgres role exists"
    community.postgresql.postgresql_user:
      name: "outline"
      password: "{{ secret_outline.postgresql_password }}" # Sadly seems required to make authentication over localhost work, for peer authentication fails somehow
      state: "present"

  - name: "Ensure database exists"
    community.postgresql.postgresql_db:
      name: "outline"
      owner: "outline"
      state: "present"

- name: "Create outline 'docker-compose.yml' file"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ outline_project_source }}/docker-compose.yml"
    owner: "outline"
    group: "outline"
    mode: "0600"

- name: "Create outline 'docker.env' file"
  ansible.builtin.template:
    src: "docker.env.j2"
    dest: "{{ outline_project_source }}/docker.env"
    owner: "outline"
    group: "outline"
    mode: "0600"

- name: "Docker compose"
  ansible.builtin.include_tasks: "../docker/tasks/compose-up.yml"
  vars:
    project_source: "{{ outline_project_source }}"

- name: "Install nginx config"
  ansible.builtin.template:
    src: "outline.conf.j2"
    dest: "/etc/nginx/sites-enabled/outline.conf"
  notify: "reload nginx"
