---
- name: "Create outline user"
  ansible.builtin.user:
    name: "outline"
    home: "{{ outline_config.home }}"
    move_home: true
    system: true
    shell: "/sbin/nologin"
    password: "!"
    create_home: false

- name: "Create home directory"
  ansible.builtin.file:
    path: "{{ outline_config.home }}"
    owner: "outline"
    group: "outline"
    mode: "2775"
    state: "directory"


- name: "Create outline directory"
  ansible.builtin.file:
    path: "{{ outline_config.project_source }}"
    state: "directory"
    owner: "outline"
    group: "outline"

- name: "Do database setup"
  become_user: "postgres"
  become: true
  block:
  - name: "Ensure Postgres role exists"
    community.postgresql.postgresql_user:
      name: "outline"
      password: "{{ secret_outline.postgresql_password }}" # TODO Sadly seems required to make authentication over localhost work, for peer authentication fails somehow. Perhaps docker networks can make this easier.
      state: "present"

  - name: "Ensure database exists"
    community.postgresql.postgresql_db:
      name: "outline"
      owner: "outline"
      state: "present"

- name: "Update configuration and migrate if needed"
  become_user: "outline"
  become: true
  block:

  - name: "Create outline 'docker-compose.yml' file"
    ansible.builtin.template:
      src: "docker-compose.yml.j2"
      dest: "{{ outline_config.project_source }}/docker-compose.yml"
      owner: "outline"
      group: "outline"
      mode: "0600"
    notify: "trigger outline migration"

  - name: "Create outline '.env' file"
    ansible.builtin.template:
      src: ".env.j2"
      dest: "{{ outline_config.project_source }}/.env"
      owner: "outline"
      group: "outline"
      mode: "0600"
    notify: "trigger outline migration"

  - name: "Check if migration must be triggered"
    ansible.builtin.meta: "flush_handlers"

  - name: "Check if migration has been triggered"
    ansible.builtin.stat:
      path: "{{ outline_config.project_source }}/.MIGRATION_PENDING"
      get_checksum: "no"
      get_attributes: "no"
      get_mime: "no"
    register: "outline_update_marker"
    changed_when: "outline_update_marker.stat.exists"
    notify: "backup outline"
    # NOTE Migration will automatically start the next time outline starts

  - name: "Start handeling migration if needed"
    ansible.builtin.meta: "flush_handlers"

  - name: "Remove migration marker"
    ansible.builtin.file:
      path: "{{ outline_config.project_source }}/.MIGRATION_PENDING"
      state: "absent"

- name: "Docker compose"
  ansible.builtin.include_tasks: "../docker/tasks/compose-up.yml"
  vars:
    project_source: "{{ outline_config.project_source }}"

- name: "Install nginx config"
  ansible.builtin.template:
    src: "outline.conf.j2"
    dest: "/etc/nginx/sites-enabled/outline.conf"
  notify: "reload nginx"
