---
# When defining a secret, define the value as a Jinja2 reference to the same
# variable name, but prefixed with "vault_", and define that key in vault.yml.
# In that way there is an overview of what secrets are used, without everyone
# having to have access to the values.

# When editing keys, be sure to read ../docs/updating-ssh-keys.md first!
# When adding admin users, be sure to add their keys to the "ansible" user too!
users:
  - name: "ansible"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "HugoPeters1024"
        state: "present"
      - username: "maartenberg"
        state: "present"
      - username: "Mstiekema"
        state: "present"
      - username: "Siem2l"
        state: "present"
      - username: "Yfkesmit"
        state: "present"
      - username: "leuke-naam"
        state: "present"
      - username: "TobiasDeBruijn"
        state: "present"
      - username: "PrinceMordred"
        state: "present"
      - username: "SanderHageman"
        state: "present"
      - username: "SilasPeters"
        state: "present"
      - username: "Riscky"
        state: "present"
      - username: "stickyPiston"
        state: "present"

  - name: "hugo"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "HugoPeters1024"
        state: "present"

  - name: "rick"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "Riscky"
        state: "present"

  - name: "sem"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "leuke-naam"
        state: "present"

  - name: "maarten"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "maartenberg"
        state: "present"

  - name: "merijn"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "Mstiekema"
        state: "present"

  - name: "siem"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "Siem2l"
        state: "present"

  - name: "lucas"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "LucasDissie"
        state: "present"

  - name: "yfke"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "Yfkesmit"
        state: "present"

  - name: "tobias"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "TobiasDeBruijn"
        state: "present"

  - name: "jack"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "PrinceMordred"
        state: "present"

  - name: "sander"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "SanderHageman"
        state: "present"

  - name: "silas"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "SilasPeters"
        state: "present"

  - name: "job"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "stickyPiston"
        state: "present"

  - name: "bestuur"
    admin: false
    sudoless_ssh: true
    home_prefix: "/var/www"
    state: "present"
    github_accounts:
      - username: "LucasDissie"
        state: "present"

  - name: "commit"
    admin: false
    home_prefix: "/var/www"
    state: "present"
    github_accounts:
      - username: "maartenberg"
        state: "present"

  - name: "dgdarc"
    admin: false
    home_prefix: "/var/www"
    state: "present"

  - name: "dies"
    admin: false
    home_prefix: "/var/www"
    state: "present"

  - name: "indievelopment"
    admin: false
    home_prefix: "/var/www"
    state: "present"

  - name: "stichting"
    admin: false
    home_prefix: "/var/www"
    state: "present"

  - name: "studytrip"
    admin: false
    home_prefix: "/var/www"
    state: "present"
    github_accounts:
      - username: "Mstiekema"
        state: "present"

  - name: "symposium"
    admin: false
    home_prefix: "/var/www"
    state: "present"
    github_accounts:
      - username: "leuke-naam"
        state: "present"

  - name: "wintersport"
    admin: false
    home_prefix: "/var/www"
    state: "present"

  - name: "snic"
    admin: false
    home_prefix: "/var/www"
    state: "present"

  - name: "pxl"
    admin: true
    home_prefix: "/var/www"
    state: "present"
    github_accounts:
      - username: "Siem2l"
        state: "present"
      - username: "SilasPeters"
        state: "present"

  - name: "hacc"
    admin: false
    home_prefix: "/var/www"
    state: "present"
    github_accounts:
      - username: "leuke-naam"
        state: "present"
      - username: "Siem2l"
        state: "present"
