---
# When defining a secret, define the value as a Jinja2 reference to the same
# variable name, but prefixed with "vault_", and define that key in vault.yml.
# In that way there is an overview of what secrets are used, without everyone
# having to have access to the values.

# When editing keys, be sure to read ../docs/updating-ssh-keys.md first!
# When adding admin users, be sure to add their keys to the "ansible" user too!
users:
  - name: "ansible"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      # May the boomers always be remembered
      - username: "HugoPeters1024"
        state: "absent"
      - username: "maartenberg"
        state: "absent"
      - username: "Riscky"
        state: "absent"
      - username: "Mstiekema"
        state: "absent"

      # Hall of history (please do not remove names, only set their state to
      # absent for lore sake)
      - username: "Siem2l"
        state: "absent"
      - username: "Yfkesmit"
        state: "absent"
      - username: "leuke-naam"
        state: "present"
      - username: "TobiasDeBruijn"
        state: "present"
      # - username: "LucasDissie"
      #   state: "absent"
      - username: "jackrosenberg"
        state: "present"
      - username: "SanderHageman"
        state: "absent"
      - username: "SilasPeters"
        state: "present"
      - username: "stickyPiston"
        state: "present"
      - username: "SamStaijen"
        state: "present"
      - username: "olafboekholt"
        state: "present"
      - username: "spookyboy99"
        state: "present"

  - name: "sem"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "leuke-naam"
        state: "present"

  - name: "tobias"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "TobiasDeBruijn"
        state: "present"

  - name: "silas"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "SilasPeters"
        state: "present"

  - name: "job"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "stickyPiston"
        state: "present"

  - name: "sam"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "SamStaijen"
        state: "present"

  - name: "olaf"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "olafboekholt"
        state: "present"

  - name: "mervin"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "spookyboy99"
        state: "present"

  - name: "jack"
    admin: true
    home_prefix: "/home"
    state: "present"
    github_accounts:
      - username: "jackrosenberg"
        state: "present"


  - name: "bestuur"
    admin: false
    sudoless_ssh: true
    home_prefix: "/var/www"
    state: "present"
    github_accounts:
      - username: "TobiasDeBruijn"
        state: "present"

  - name: "commit"
    admin: false
    home_prefix: "/var/www"
    state: "present"
    github_accounts:
      - username: "maartenberg"
        state: "absent"

  - name: "dgdarc"
    admin: false
    home_prefix: "/var/www"
    state: "present"

  - name: "dies"
    admin: false
    home_prefix: "/var/www"
    state: "present"

  - name: "indievelopment"
    admin: false
    home_prefix: "/var/www"
    state: "present"

  - name: "stichting"
    admin: false
    home_prefix: "/var/www"
    state: "present"

  - name: "studytrip"
    admin: false
    home_prefix: "/var/www"
    state: "present"
    github_accounts:
      - username: "Mstiekema"
        state: "absent"

  - name: "symposium"
    admin: false
    home_prefix: "/var/www"
    state: "present"
    github_accounts:
      - username: "leuke-naam"
        state: "absent"

  - name: "wintersport"
    admin: false
    home_prefix: "/var/www"
    state: "present"

  - name: "snic"
    admin: false
    home_prefix: "/var/www"
    state: "present"

  - name: "pxl"
    admin: true
    home_prefix: "/var/www"
    state: "present"
    github_accounts:
      - username: "SilasPeters"
        state: "present"
      - username: "olafboekholt"
        state: "present"

  - name: "hacc"
    admin: false
    home_prefix: "/var/www"
    state: "present"
    github_accounts:
      - username: "leuke-naam"
        state: "absent"
      - username: "Siem2l"
        state: "absent"
