---
# When defining a secret, define the value as a Jinja2 reference to the same
# variable name, but prefixed with "vault_", and define that key in vault.yml.
# In that way there is an overview of what secrets are used, without everyone
# having to have access to the values.

server_hostname: "sadserver"
canonical_hostname: "{{ inventory_hostname }}"

tmp_dir: "/tmp"

unattended_upgrades:
  security: true
  all: true

fail2ban:
  loglevel: "WARNING"
  ignoreip: "127.0.0.1/8 131.211.0.0/16"
  bantime: 600
  maxretry: 6
  banaction: "iptables-multiport"

  services:
    - name: "sshd"
      port: "ssh"
      filter: "sshd"
      logpath: "/var/log/auth.log"
    - name: "koala"
      port: "https"
      filter: "koala"
      logpath:
        "/var/www/koala.{{ canonical_hostname }}/log/\
        {{ koala_env.environment }}.log"
      maxretry: 10
    - name: "koala404"
      port: "https"
      filter: "koala404"
      logpath: "/var/www/koala.{{ canonical_hostname }}/log/access.log"
      findtime: 60
      maxretry: 5

# the upload limit for php-fpm and nginx in megabytes
upload_limit: 30

slack_notifications:
  default_channel: "notifications"
  slacktee:
    repo: "https://github.com/course-hero/slacktee.git"
    install_path: "/usr/local/src/slacktee"
  # To change, regenerate the webhook URL here:
  # https://svsticky.slack.com/apps/A0F7XDUAZ-incoming-webhooks
  webhook_url: "{{ vault_slack_notifications_webhook_url }}"

aws_region: "eu-west-1"

# Koala's environment-specific vars are defined in their respective file with
# group_vars, in the dict "koala_env"
koala:
  server: "unicorn" # or webrick
  ruby_version: "2.5.3"
  threads: 6
  dependencies:
    - repo: "rbenv"
      install_path: "~/.rbenv"
    - repo: "ruby-build"
      install_path: "~/.rbenv/plugins/ruby-build"
    - repo: "rbenv-vars"
      install_path: "~/.rbenv/plugins/rbenv-vars"

# The key for our machine user on GitHub, which is used to clone private
# projects.
# To change, generate SSH key and replace it at https://github.com/settings/keys
# when logged in as the machine user
secret_deploy_key: "{{ vault_secret_deploy_key }}"

# The API key for our Mailgun account.
# Change? Refresh API key at https://app.mailgun.com/app/account/security
secret_mailgun_token: "{{ vault_secret_mailgun_token }}"
