---
# When defining a secret, define the value as a Jinja2 reference to the same
# variable name, but prefixed with "vault_", and define that key in vault.yml.
# In that way there is an overview of what secrets are used, without everyone
# having to have access to the values.

server_hostname: "sadserver"
canonical_hostname: "{{ inventory_hostname }}"

tmp_dir: "/tmp"

# the upload limit for nginx in megabytes
upload_limit: 30

slack_notifications:
  default_channel: "notifications"
  # To change, regenerate the webhook URL here:
  # https://svsticky.slack.com/apps/A0F7XDUAZ-incoming-webhooks
  webhook_url: "{{ vault_slack_notifications_webhook_url }}"

aws_region: "eu-west-1"

# The key for our machine user on GitHub, which is used to clone private
# projects.
# To change, generate SSH key and replace it at https://github.com/settings/keys
# when logged in as the machine user
secret_deploy_key: "{{ vault_secret_deploy_key }}"

# The API key for our Mailgun account.
# Change? Refresh API key at https://app.mailgun.com/app/account/security
secret_mailgun_token: "{{ vault_secret_mailgun_token }}"

# The place where https://github.com/nvm-sh/nvm will be installed, to be globally used
nvm:
  directory: "/usr/local/bin/.nvm"
  script: "/usr/local/bin/.nvm/nvm.sh"
  version: "v0.40.0" # Derived from the git tag

uv:
  install_dir: /usr/local/bin
  version: 0.5.14
