---
- name: "create committee group"
  ansible.builtin.group:
    name: "committee"
    state: "present"

- name: "create sudoless_ssh group"
  ansible.builtin.group:
    name: "sudoless_ssh"
    state: "present"

- name: "create /var/www"
  ansible.builtin.file:
    path: "/var/www"
    state: "directory"

# When users are deleted here, their home directory is not. Run
# ../playbooks/purge-old-users.yml for that.
- name: "create/delete users"
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{% if item.admin %}sudo,adm{% elif item.sudoless_ssh | default(False) %}sudoless_ssh{% else %}committee{% endif %}"
    shell: "{{ '/bin/bash' if item.admin or (item.sudoless_ssh | default(False)) else omit }}"
    home: "{{ item.home_prefix }}/{{ item.name }}"
    move_home: true
    state: "{{ item.state }}"
  with_items:
    - "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

# This user is can do passwordless sudo, which is necessary from some
# installation routines like nix
- name: "create eindbaas user"
  ansible.builtin.user:
    name: "eindbaas"
    state: "present"
    shell: "/bin/false"
    system: true
    home: "/var/lib/eindbaas/"
    password: "!"


- name: "fix permissions for chroot of committee users"
  ansible.builtin.file:
    path: "{{ item.home_prefix }}/{{ item.name }}"
    owner: "root"
    state: "directory"
  when:
    # List is evaluated as logical AND
    - not item.admin
    - item.state == 'present'
  with_items:
    - "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: "add environment to bash prompt of admins"
  ansible.builtin.lineinfile:
    dest: "{{ item.home_prefix }}/{{ item.name }}/.bashrc"
    regexp: "^export PS1="
    line: "{{ bash_prompt }}"
  when: item.admin and item.state == 'present'
  with_items:
    - "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: "add environment to bash prompt of root"
  ansible.builtin.lineinfile:
    dest: "/root/.bashrc"
    regexp: "^export PS1="
    line:
      "{{ bash_prompt | regex_replace('\\$ ', '# ') }}"
