---

- name: "create user for undead mongoose"
  ansible.builtin.user:
    name: "mongoose"
    home: "/var/www/mongoose"
    shell: "/usr/sbin/nologin"
    state: "present"
    system: true

- name: "copy nginx configuration"
  ansible.builtin.template:
    src: "mongoose.conf.j2"
    dest: "/etc/nginx/sites-available/mongoose.{{ canonical_hostname }}.conf"
  notify: "reload nginx"

- name: "enable nginx configuration"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/mongoose.{{ canonical_hostname }}.conf"
    path: "/etc/nginx/sites-enabled/mongoose.{{ canonical_hostname }}.conf"
    state: "link"
  notify: "reload nginx"

- block:
  - name: "ensure mongoose user exists"
    community.postgresql.postgresql_user:
      name: "mongoose"

  - name: "ensure mongoose database exists"
    community.postgresql.postgresql_db:
      name: "mongoose"
      owner: "mongoose"

  - name: "ensure mongoose database exists"
    community.postgresql.postgresql_user:
      db: "mongoose"
      name: "mongoose"
      priv: "ALL"
      role_attr_flags: "CREATEDB,LOGIN"

  become_user: "postgres"

- block:
  - name: "ensure mongoose has a ssh directory"
    ansible.builtin.file:
      path: "~/.ssh"
      state: "directory"

  - name: "copy deploy key for private projects on GitHub"
    ansible.builtin.copy:
      content: "{{ secret_deploy_key }}"
      dest: "/var/www/mongoose/.ssh/id_ed25519"
      mode: "0600"

  - name:
      "clone mongoose repository"
    ansible.builtin.git:
      repo: "git@github.com:svsticky/undead-mongoose"
      dest: "/var/www/mongoose/undead-mongoose"
      depth: 1
      force: true
      version: "master"
    diff: false
    register: "mongoose_clone"
    notify: "restart mongoose"

  - name:
      "template environment file for mongoose"
    ansible.builtin.template:
      src: ".env.j2"
      dest: "/var/www/mongoose/undead-mongoose/.env"
    diff: false
    notify: "restart mongoose"

  - name:
      "run migrations"
    ansible.builtin.command: "/nix/var/nix/profiles/default/bin/nix-shell --run 'dotenv ./manage.py migrate'"
    args:
      chdir: "/var/www/mongoose/undead-mongoose"
    when: "mongoose_clone is changed"
    notify: "restart mongoose"

  become_user: "mongoose"

- name: "template systemd service file for mongoose"
  ansible.builtin.template:
    src: "mongoose.service.j2"
    dest: "/etc/systemd/system/mongoose.service"
  notify: "restart mongoose"

- name: "flush_handlers"
  ansible.builtin.meta: "flush_handlers"

- name: "ensure mongoose service is running"
  ansible.builtin.systemd:
    name: "mongoose.service"
    state: "started"
    enabled: true
