---
- name: "check if koala is running"
  systemd:
    name: "koala.service"
    state: "started"
  check_mode: true
  register: "koala_running"
  listen: "restart koala"

- name: "restart oauth2-proxy"
  service:
    name: "oauth2-proxy"
    state: "restarted"
  listen: "restart oauth2-proxy"

- name: "restart koala service"
  service:
    name: "koala"
    state: "restarted"
  when: "koala_running is not changed"
  listen: "restart koala"

- name: "restart fail2ban"
  service:
    name: "fail2ban"
    state: "restarted"

- name: "restart redis"
  service:
    name: "redis-server"
    state: "restarted"

- name: "restart mariadb"
  service:
    name: "mysql"
    state: "restarted"

- name: "test nginx configuration"
  command: "nginx -t"
  listen: "reload nginx"

- name: "reload nginx service"
  service:
    name: "nginx"
    state: "reloaded"
  listen: "reload nginx"

- name: "reload php"
  service:
    name: "php7.2-fpm"
    state: "reloaded"

- name: "systemctl daemon-reload"
  systemd:
    daemon_reload: true

- name: "issue reboot command"
  shell: "sleep 2 && /sbin/reboot"
  async: 60
  poll: 0
  ignore_errors: true
  listen: "reboot server"

- name: "wait for server to finish rebooting"
  wait_for_connection:
    delay: 20
  listen: "reboot server"

- name: "restart aas"
  systemd:
    unit: "aas.service"
    state: "restarted"
