---
- name: "test nginx configuration"
  ansible.builtin.command: "nginx -t"
  listen: "reload nginx"

- name: "reload nginx service"
  ansible.builtin.service:
    name: "nginx"
    state: "reloaded"
  listen: "reload nginx"

- name: "systemctl daemon-reload"
  ansible.builtin.systemd:
    daemon_reload: true

- name: "issue reboot command"
  ansible.builtin.shell: "sleep 2 && /sbin/reboot"
  async: 60
  poll: 0
  ignore_errors: true
  listen: "reboot server"

- name: "wait for server to finish rebooting"
  ansible.builtin.wait_for_connection:
    delay: 20
  listen: "reboot server"
