- name: "ensure koala is running"
  service:
    name: "koala"
    enabled: true
    state: "started"
  become: true
  become_user: "root"

- name: "disable Koala's maintenance mode"
  file:
    state: "absent"
    path: "/var/www/koala.{{ canonical_hostname }}/MAINTENANCE_MODE"
  become: true
  become_user: "koala"
