---
- hosts: "all"
  remote_user: "ansible"
  force_handlers: true

  vars_prompt:
    - name: "admin_to_remove"
      default: ""
      prompt: "Please enter the username to remove: (Ctrl-C to cancel)"
      private: false

  tasks:
    - assert:
        that:
          - "admin_to_remove != ''"

    - name: "remove admin"
      shell:
        'bin/rails "admin:delete[{{ admin_to_remove}}]"'
      args:
        chdir: "/var/www/koala.{{ canonical_hostname }}"
        executable: "/bin/bash"
      register: "result"
      become: true
      become_user: "koala"

    - debug:
        var: "result.stdout_lines"
