---
- hosts: "all"
  remote_user: "ansible"
  force_handlers: true

  vars_prompt:
    - name: "rake_task"
      prompt: "Enter task to execute:"
      private: false

  tasks:
    - name: "custom rake task"
      shell:
        'bin/rails {{ rake_task }}'
      args:
        chdir: "/var/www/koala.{{ canonical_hostname }}"
        executable: "/bin/bash"
      register: "result"
      become: true
      become_user: "koala"

    - debug:
        var: "result.stdout_lines"
