---
- name: "clone nvm"
  listen: "radio repo updated"
  become_user: "radio"
  become: true
  ansible.builtin.git:
    repo: "https://github.com/nvm-sh/nvm.git"
    dest: "/var/www/radio/.nvm"
    recursive: false # cloning submodules fails, but they are purely for testing
  diff: false

- name: "checkout latest nvm version" # based on nvm manual installation guide
  listen: "radio repo updated"
  become_user: "radio"
  become: true
  ansible.builtin.shell:
    cmd: git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
    chdir: "/var/www/radio/.nvm"
    executable: "/bin/bash"
  tags:
    - skip_ansible_lint
    # Reason: linter wants us to use the git module, but that can't do this
    # complicated stuff

- name: "install node version"
  listen: "radio repo updated"
  become_user: "radio"
  become: true
  ansible.builtin.shell: |
    source /var/www/radio/.nvm/nvm.sh
    nvm install $(cat /var/www/radio/radio/.nvmrc)
  args:
    chdir: "/var/www/radio/radio"
    executable: "/bin/bash"
  notify: "radio node version changed"

- name: "run npm rebuild if needed"
  listen: "radio node version changed"
  become_user: "radio"
  become: true
  ansible.builtin.shell: |
    source /var/www/radio/.nvm/nvm.sh
    nvm use
    npm rebuild
  args:
    chdir: "/var/www/radio/radio"
    executable: "/bin/bash"
