---

- name: "install node version"
  listen: "radio repo updated"
  become_user: "radio"
  become: true
  ansible.builtin.shell: |
    source {{ nvm.script }}
    nvm install $(cat /var/www/radio/radio/.nvmrc)
  args:
    chdir: "/var/www/radio/radio"
    executable: "/bin/bash"
  notify: "radio node version changed"

- name: "run npm rebuild if needed"
  listen: "radio node version changed"
  become_user: "radio"
  become: true
  ansible.builtin.shell: |
    source {{ nvm.script }}
    nvm use
    npm rebuild
  args:
    chdir: "/var/www/radio/radio"
    executable: "/bin/bash"
