---
- name: "remove help text from motd"
  ansible.builtin.file:
    path: "/etc/update-motd.d/{{ item }}"
    state: "absent"
  with_items:
    - "10-help-text"
    - "51-cloudguest"

- name: "copy motd templates"
  ansible.builtin.template:
    src: "motd/{{ item }}.j2"
    dest: "/etc/update-motd.d/{{ item }}"
    mode: "0755"
  with_items:
    - "01-sadserver-header"
    - "02-playbook-revision"

# In staging we just use the name that is set when creating our VPS.
- name: "set custom hostname, in production"
  ansible.builtin.hostname:
    name: "{{ server_hostname }}"
  when: "'staging' not in group_names"

# In staging we just use the name that is set when creating our VPS.
- name: "update hostname in /etc/hosts, in production"
  ansible.builtin.lineinfile:
    regexp: "^127.0.1.1"
    line:
      "127.0.1.1 {{ server_hostname }}.{{ canonical_hostname }}
      {{ server_hostname }}"
    path: "/etc/hosts"
    state: "present"
  when: "'staging' not in group_names"

- name: "copy locale variables"
  ansible.builtin.template:
    src: "locale.j2"
    dest: "/{{ path }}"
  vars:
    path: "etc/default/locale"

- name: "copy failure handler for systemd units"
  ansible.builtin.template:
    src: "failure-notificator@.service.j2"
    dest: "/etc/systemd/system/failure-notificator@.service"
  notify: "systemctl daemon-reload"
