---
- name: "create user"
  ansible.builtin.user:
    name: "keycloak"
    home: "{{ keycloak_project_source }}"
    shell: "/usr/sbin/nologin"
    state: "present"
    system: true

- name: "set up keycloak"
  become_user: "keycloak"
  become: true
  block:
  - name: "clone repository"
    ansible.builtin.git:
      repo: "https://github.com/svsticky/improved-adventure.git"
      dest: "{{ keycloak_project_source }}/app"
      depth: 1
      version: main #"{% if 'production' in group_names %}main{% else %}development{% endif %}" # Pull main when deploying to prod
    diff: false

  - name: "Copy .env file"
    ansible.builtin.template:
      src: ".env.j2"
      dest: "{{ keycloak_project_source }}/app/.env"
    diff: false

  - name: "Docker compose"
    ansible.builtin.include_tasks: "../docker/tasks/compose-up.yml"
    vars:
      project_source: "{{ keycloak_project_source }}/app"
      remove_images: all

- name: "Copy nginx configuration"
  ansible.builtin.template:
    src: "keycloak.conf.j2"
    dest: "/etc/nginx/sites-available/keycloak.{{ canonical_hostname }}.conf"
  notify: "reload nginx"

- name: "Enable nginx configuration for keycloak"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/keycloak.{{ canonical_hostname }}.conf"
    path: "/etc/nginx/sites-enabled/keycloak.{{ canonical_hostname }}.conf"
    state: link
  notify: "reload nginx"
