---
- name: "install composer"
  apt:
    name:
      - "composer"
      - "php7.4-curl"
      - "php7.4-bcmath"
    state: "present"
  become: true

- name: "disable git safe directory feature for digidecs folder" # noqa command-instead-of-module
  command: "git config --global --add safe.directory /var/www/commit/digidecs.{{ canonical_hostname }}"

- name: "clone digidecs repository"
  git:
    repo: "https://github.com/svsticky/digidecs.git"
    dest: "/var/www/commit/digidecs.{{ canonical_hostname }}"
    version: "master"
  diff: false

- name: "place config file"
  template:
    src: "config.php.j2"
    dest: "/var/www/commit/digidecs.{{ canonical_hostname }}/config.php"
    owner: "www-data"
    group: "commit"
    mode: "660"

- name: "copy nginx configuration"
  template:
    src: "digidecs.conf.j2"
    dest: "/etc/nginx/sites-available/digidecs.{{ canonical_hostname }}.conf"
  notify: "reload nginx"

- name: "enable nginx configuration"
  file:
    src: "/etc/nginx/sites-available/digidecs.{{ canonical_hostname }}.conf"
    path: "/etc/nginx/sites-enabled/digidecs.{{ canonical_hostname }}.conf"
    state: "link"
  notify: "reload nginx"

- name: "run composer"
  composer:
    working_dir: "/var/www/commit/digidecs.{{ canonical_hostname }}"
    command: "install"

- name: "set permissions on digidecs files"
  file:
    path: "/var/www/commit/digidecs.{{ canonical_hostname }}"
    owner: "www-data"
    group: "commit"
    recurse: true
    state: "directory"
