---
- name: "Create user for digidecs"
  ansible.builtin.user:
    name: digidecs
    home: "{{ digidecs_config.home }}"
    shell: "/usr/sbin/nologin"
    system: true
    state: "present"
    create_home: false

- name: "Create home directory"
  ansible.builtin.file:
    path: "{{ digidecs_config.home }}"
    owner: "digidecs"
    group: "digidecs"
    mode: "2775"
    state: "directory"

- name: "Create digidecs frontend directory"
  ansible.builtin.file:
    name: "{{ digidecs_config.home }}/frontend"
    owner: "digidecs"
    group: "digidecs"
    mode: "2775"
    state: "directory"

- name: "Create digidecs server directory"
  ansible.builtin.file:
    name: "{{ digidecs_config.home }}/server"
    owner: "digidecs"
    group: "digidecs"
    mode: "2775"
    state: "directory"

- name: "install dependencies"
  ansible.builtin.apt:
    name:
      - "python3-dotenv-cli"
    state: "present"

- name: "Determine base url to online artifacts to deploy"
  ansible.builtin.set_fact:
    artifact_base_url: "https://github.com/svsticky/digidecs/releases/{% if digidecs.git_tag == 'latest' %}latest/download{% else %}download/{{ digidecs.git_tag }}{% endif %}"

- name: "Download and extract digidecs frontend"
  ansible.builtin.unarchive:
    src: "{{ artifact_base_url }}/frontend.tar.gz"
    dest: "{{ digidecs_config.home }}/frontend"
    remote_src: true
    owner: "digidecs"
    group: "digidecs"
    mode: "775"
    extra_opts:
    - "--strip-components=1"

- name: "Download and extract digidecs server"
  ansible.builtin.get_url:
    url: "{{ artifact_base_url }}/server-x86_64-unknown-linux-musl"
    dest: "{{ digidecs_config.home }}/server"
    owner: "digidecs"
    group: "digidecs"
    mode: "775"
  notify: "restart digidecs"

- name: "Copy nginx configuration"
  ansible.builtin.template:
    src: "digidecs.conf.j2"
    dest: "/etc/nginx/sites-enabled/digidecs.{{ canonical_hostname }}.conf"
  notify: "reload nginx"

- name: "Template environment file for digidecs"
  ansible.builtin.template:
    src: "env.j2"
    dest: "{{ digidecs_config.home }}/server/.env"
  diff: false
  notify: "restart digidecs"

- name: "Template config file for digidecs"
  ansible.builtin.template:
    src: "digidecs.json.j2"
    dest: "{{ digidecs_config.home }}/server/config.json"
  diff: false
  notify: "restart digidecs"

- name: "template systemd service file for digidecs"
  ansible.builtin.template:
    src: "digidecs.service.j2"
    dest: "/etc/systemd/system/digidecs.service"
  notify: "restart digidecs"

- name: "run digidecs service"
  ansible.builtin.systemd:
    unit: "digidecs.service"
    state: "started"
    enabled: true
    daemon-reload: true
