---
- name: "create user for digidecs"
  ansible.builtin.user:
    name: "digidecs"
    home: "/var/www/digidecs/"
    shell: "/usr/sbin/nologin"
    system: true

- name: "install composer"
  ansible.builtin.apt:
    name:
      - "composer"
      - "php7.4-curl"
      - "php7.4-bcmath"
    state: "present"
  become: true

- name: "disable git safe directory feature for digidecs folder" # noqa command-instead-of-module
  ansible.builtin.command: "git config --global --add safe.directory /var/www/digidecs.{{ canonical_hostname }}"

- name: "clone digidecs repository"
  ansible.builtin.git:
    repo: "https://github.com/svsticky/digidecs.git"
    dest: "/var/www/digidecs.{{ canonical_hostname }}"
    version: "master"
  diff: false

- name: "place config file"
  ansible.builtin.template:
    src: "config.php.j2"
    dest: "/var/www/digidecs.{{ canonical_hostname }}/config.php"
    owner: "digidecs"
    group: "digidecs"
    mode: "660"

- name: "copy nginx configuration"
  ansible.builtin.template:
    src: "digidecs.conf.j2"
    dest: "/etc/nginx/sites-available/digidecs.{{ canonical_hostname }}.conf"
  notify: "reload nginx"

- name: "enable nginx configuration"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/digidecs.{{ canonical_hostname }}.conf"
    path: "/etc/nginx/sites-enabled/digidecs.{{ canonical_hostname }}.conf"
    state: "link"
  notify: "reload nginx"

- name: "run composer"
  community.general.composer:
    working_dir: "/var/www/digidecs.{{ canonical_hostname }}"
    command: "install"

- name: "set permissions on digidecs files"
  ansible.builtin.file:
    path: "/var/www/digidecs.{{ canonical_hostname }}"
    owner: "digidecs"
    group: "digidecs"
    recurse: true
    state: "directory"
