---
# Needed because of Ansible issue #25414
- name: "check if unattended-upgrades is not in progress"
  shell:
    "while fuser /var/lib/dpkg/lock; do sleep 1; done;"
  become: true
  changed_when: false

- name: "install common utilities"
  apt:
    name:
      - "aptitude"
      - "htop"
      - "unattended-upgrades"
      - "haveged"
      - "jq"
      - "nginx"
      - "acl"
      - "git"
      - "toilet"
      - "python3-dotenv-cli"
    state: "present"

- name: "update all packages"
  apt:
    upgrade: "yes"
    update_cache: true
    cache_valid_time: 100

- name: "set apt unattended-upgrades settings"
  template:
    src: "50unattended-upgrades.j2"
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"

- name: "configure unattended-upgrades"
  file:
    path: "/etc/systemd/system/{{ item }}"
    state: "absent"
  with_items:
    - "unattended-upgrades-output.service"
    - "unattended-upgrades-output.timer"
  notify:
    - "systemctl daemon-reload"

# slacktee is the tool we use to let the server send notifications to Slack.
# Replaces email.
# Only ensure repository is cloned, don't update yet
- name: "clone repository of slacktee"
  git:
    repo: "{{ slacktee.repo }}"
    dest: "{{ slacktee.install_path }}"
    update: false
  diff: false

- name: "retrieve all version numbers of slacktee" # noqa command-instead-of-module
  command: "git fetch --tags"
  args:
    chdir: "{{ slacktee.install_path }}"
  register: "slacktee_fetch"
  changed_when: slacktee_fetch.stdout != ""

- name: "determine latest version number of slacktee" # noqa command-instead-of-module
  shell: "git describe --tags $(git rev-list --tags --max-count=1)"
  args:
    chdir: "{{ slacktee.install_path }}"
  register: "slacktee_version"
  # The next task already shows if there is actually a change
  changed_when: false

# Wrapped in block because otherwise templating is done before skipping task,
# which will fail in check mode
- block:
  - name: "install newest release of slacktee"
    git:
      repo: "{{ slacktee.repo }}"
      dest: "{{ slacktee.install_path }}"
      version: "v1.5.1"
    diff: false
  # Don't run in check mode because previous "git fetch" task also can't be run
  # in check mode
  when: not ansible_check_mode

- name: "create symlink to slacktee in $PATH"
  file:
    src: "{{ slacktee.install_path }}/{{ filename }}.sh"
    path: "/usr/local/bin/{{ filename }}"
    state: "link"
  vars:
    filename: "slacktee"

- name: "configure slacktee"
  template:
    src: "slacktee.conf"
    dest: "/etc/slacktee.conf"
