---
secrets_environment_directory: "staging"

# This is also used for the root user, but the "$" at the end is replaced by a
# "#" through a regex in tasks/users.yml.
bash_prompt:
  "export PS1='\\n\\e[31m\\e[1mSTAGING\\e[0m \\e[33m\\e[1m`whoami`@`hostname \
  --long`\\e[0m:`pwd`\\n$ '"

koala_env:
  environment: "staging"
  git_ref: "development"
