---
koala_environment: production       # 'development' or 'production'
koala_version: master               # Git reference to clone
koala_ruby_version: 2.3.0           # Used when rbenv is not yet available
