---
 - hosts: all
   vars:
       koala_environment: development
       koala_version: development

   tasks:

     # Privileged tasks:
   - block:

     - include: tasks/auth.yml
     - include: tasks/database.yml

     - include: tasks/koala.yml

     become: yes

   handlers:
     - name: systemctl daemon-reload
       command: systemctl daemon-reload
       become: yes

   # As user 'koala':
   #- block:

     ##- name: rake routes
       ##environment:
         ##PATH: "/home/koala/.rbenv/bin:{{ ansible_env.PATH }}"
       ##shell: eval "$(rbenv init - )"; bundle exec rake routes
       ##args:
         ##chdir: /var/www/koala.svsticky.nl

     ##- name: ensure database exists
       ##environment:
         ##PATH: "/home/koala/.rbenv/bin:{{ ansible_env.PATH }}"
       ##shell: eval "$(rbenv init - )"; bundle exec rake RAILS_ENV={{ koala_environment }} db:setup
       ##args:
         ##chdir: /var/www/koala.svsticky.nl

     #become: yes
     #become_user: koala


# TODO:
#  - Should (part of) this setup be included in the koala project's Vagrantfile?
#  - Install nginx (skyblue playbook does this already, but is not virtualboxable)
#  - Set up database (mariadb)
#     Autogenerate credentials with password lookup, hardcode with vault lookup, or?
#  - Set up unicorn
#     -> Convert to systemd service?
#  - Set up cronjobs
#     Perhaps systemd timers are useful, manually startable etc.
#  - Create koala's db
