---
 - hosts: all
   vars_files:
       - environment.yml

   tasks:

     # Privileged tasks:
   - block:

     - include: tasks/auth.yml
     - include: tasks/database.yml

     - include: tasks/koala.yml

     become: yes

   handlers:
     - name: systemctl daemon-reload
       command: systemctl daemon-reload
       become: yes

# TODO:
#  - Should (part of) this setup be included in the koala project's Vagrantfile?
#  - Install nginx (skyblue playbook does this already, but is not virtualboxable)
#  - Set up cronjobs
#     Perhaps systemd timers are useful, manually startable etc.
