# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use Ubuntu 14.04 Trusty Tahr 64-bit as our operating system
  config.ssh.forward_agent = true
  config.vm.box = 'bento/ubuntu-16.04'
  config.vm.hostname = 'xenial-koala'

  # Configurate the virtual machine to use 2GB of RAM
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--memory', '2048']
  end

  # Forward the Rails server default port to the host
  config.vm.network :forwarded_port, guest: 3000, host: 3000

  # Forward the nginx server's ports
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 443, host: 4443

  # Use Ansible to prepare Ansible (install python)
  config.vm.provision "ansible_bootstrap", type: "ansible" do |ansible|
    ansible.playbook = "bootstrap.yml"
  end
  # Use Ansible to provision our virtual machine
  config.vm.provision "main", type: "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
