---
- name: "ensure pretix user is present"
  user:
    name: "pretix"
    home: "/var/www/pretix"
    system: true

- name: "ensure dependencies are present"
  apt:
    name:
      - "git"
      - "build-essential"
      - "python-dev"
      - "python3-virtualenv"
      - "python3"
      - "python3-pip"
      - "python3-dev"
      - "libxml2-dev"
      - "libxslt1-dev"
      - "libffi-dev"
      - "zlib1g-dev"
      - "libssl-dev"
      - "gettext"
      - "libpq-dev"
      - "libjpeg-dev"
    state: "present"

- name: "setup Pretix database"
  become_user: "postgres"
  block:
  - name: "ensure Pretix database user exists"
    postgresql_user:
      name: "pretix"
      state: "present"

  - name: "ensure database exists"
    postgresql_db:
      name: "pretix"
      owner: "pretix"
      state: "present"
    notify: "pretix post-upgrade"

- name: "ensure pretix config directories are present"
  file:
    path: "{{ item }}"
    state: "directory"
    owner: "pretix"
    group: "pretix"
  with_items:
    - "/etc/pretix"
    - "/var/www/pretix/data/media"

- name: "place pretix config file"
  template:
    src: "pretix.cfg.j2"
    dest: "/etc/pretix/pretix.cfg"
    owner: "pretix"
    group: "pretix"
    mode: "0600"
  notify: "restart pretix"

- name: "create virtualenv if not exists, update pip and tools"
  pip:
    name:
      - "pip"
      - "setuptools"
      - "wheel"
    state: "latest"
    virtualenv: "/var/www/pretix/venv"
    virtualenv_python: "python3.8"
  become: true
  become_user: "pretix"

- name: "place pretix's service files"
  template:
    src: "systemd/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - "pretix-web.service"
    - "pretix-worker.service"
    - "pretix-runperiodic.service"
    - "pretix-runperiodic.timer"
  notify:
    - "systemctl daemon-reload"
    - "restart pretix"

- name: "install pretix"
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: "present"
    virtualenv: "/var/www/pretix/venv"
    virtualenv_python: "python3.9"
  with_items:
    - name: "gunicorn"
      version: "20.1.0"
    - name: "pretix"
      version: "4.8.0"
    - name: "pretix-pages"
      version: "1.4.1"
    - name: "pretix-mollie"
      version: "1.3.2"
    - name: "pretix-fontpack-free"
      version: "1.7.0"
    - name: "psycopg2"
      version: "2.9.3"
  notify:
    - "pretix post-upgrade"
    - "restart pretix"
  become: true
  become_user: "pretix"

- name: "Ensure daemon is reloaded"
  meta: "flush_handlers"

- name: "ensure pretix services are running and enabled"
  service:
    name: "{{ item }}"
    state: "started"
    enabled: "yes"
  with_items:
    - "pretix-web.service"
    - "pretix-worker.service"
    - "pretix-runperiodic.timer"

- name: "place pretix's nginx configuration"
  template:
    src: "pretix.conf.j2"
    dest: "/etc/nginx/sites-available/{{ dest_filename }}"
  vars:
    dest_filename: "pretix.{{ canonical_hostname }}.conf"
  notify: "reload nginx"

- name: "enable pretix's nginx configuration"
  file:
    src: "/etc/nginx/sites-available/{{ filename }}"
    dest: "/etc/nginx/sites-enabled/{{ filename }}"
    state: "link"
  vars:
    filename: "pretix.{{ canonical_hostname }}.conf"
  notify: "reload nginx"
