---

- name: "restart outline"
  # when: "_outline_checkout is changed
  #     or _outline_service_file is changed
  #     or _outline_env_file is changed"
  ansible.builtin.systemd:
    name: "outline.service"
    state: "restarted"
    daemon_reload: true

- name: "install dependencies"
  become_user: "outline"
  become: true
  ansible.builtin.command: "yarn install --frozen-lockfile"
  args:
    chdir: "/var/www/outline/outline"
  listen: "yarn install"

- name: "build outline"
  become_user: "outline"
  become: true
  ansible.builtin.command: "yarn build"
  args:
    chdir: "/var/www/outline/outline"
  listen: "yarn build"
