---
- name: "install fail2ban"
  ansible.builtin.apt:
    name: "fail2ban"
    state: "present"

- name: "flush handlers so the files exist that fail2ban monitors"
  ansible.builtin.meta: "flush_handlers"

- name: "create directory for onfailure override for fail2ban service"
  ansible.builtin.file:
    path: "/etc/systemd/system/fail2ban.service.d"
    state: "directory"

- name: "copy onfailure override for fail2ban service"
  ansible.builtin.template:
    src: "onfailure.conf.j2"
    dest: "/etc/systemd/system/fail2ban.service.d/onfailure.conf"
  notify: "systemctl daemon-reload"

- name: "configure fail2ban"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/fail2ban/{{ item }}"
  loop:
    - "fail2ban.local"
    - "jail.local"
    - "filter.d/koala.conf"
    - "filter.d/koala404.conf"
  notify: "restart fail2ban"

- name: "start and enable fail2ban"
  ansible.builtin.service:
    name: "fail2ban"
    state: "started"
    enabled: true
