---
- name: "enable Koala's maintenance mode"
  ansible.builtin.file:
    state: "touch"
    path: "/home/koala/MAINTENANCE_MODE"
  become: true
  become_user: "koala"

- name: "ensure sidekiq background worker is not running"
  ansible.builtin.service:
    name: "sidekiq"
    state: "stopped"
  ignore_errors: true
  become: true
  become_user: "root"

- name: "ensure koala is not running"
  ansible.builtin.service:
    name: "koala"
    state: "stopped"
  become: true
  become_user: "root"
