---
- name: "ensure koala is running"
  ansible.builtin.service:
    name: "koala"
    enabled: true
    state: "started"
  become: true
  become_user: "root"

- name: "ensure sidekiq background worker is running"
  ansible.builtin.service:
    name: "sidekiq"
    state: "started"
  become: true
  become_user: "root"

- name: "disable Koala's maintenance mode"
  ansible.builtin.file:
    state: "absent"
    path: "/home/koala/MAINTENANCE_MODE"
  become: true
  become_user: "koala"
