---
- name: "ensure ipv6 firewalling is enabled"
  ansible.builtin.lineinfile:
    dest: "/etc/default/ufw"
    regexp: "^IPV6="
    line: "IPV6=yes"
    state: "present"

- name: "allow incoming traffic on specified ports"
  community.general.ufw:
    rule: "allow"
    to_port: "{{ item }}"
  with_items:
    - "ssh"
    - "http"
    - "https"

- name: "allow outgoing traffic"
  community.general.ufw:
    policy: "allow"
    direction: "outgoing"
    state: "enabled"

- name: "block all other incoming traffic"
  community.general.ufw:
    policy: "deny"
    direction: "incoming"
    state: "enabled"
