---
- hosts: all

  vars_files:
      - "../vars.yml"

  vars_prompt:
      - name: "new_admins_username"
        default: "admin@localhost"
        prompt: "Please enter the new admin user's email."
        private: false

      - name: "new_admins_password"
        default: "sticky123"
        prompt: "Please enter the new admin user's password."
        private: true

      - name: "password_confirm"
        prompt: "Enter the password again for confirmation."
        private: true

  tasks:
      - assert:
          that:
            - "new_admins_password == password_confirm"

      - name: "create admin"
        environment:
          PATH: "/home/koala/.rbenv/bin:{{ ansible_env.PATH }}"
        shell: 'eval "$(rbenv init - )"; bin/rails RAILS_ENV={{ koala.environment }} "admin:create[{{ new_admins_username }}, {{ new_admins_password }}]"'
        args:
          chdir: "/var/www/koala.{{ canonical_hostname }}"
          executable: "/bin/bash"
        register: "result"
        become: true
        become_user: "koala"

      - debug:
          var: "result.stdout_lines"
