---
- hosts: all
  vars_files:
      - ../vars.yml

  tasks:
    - block:
      - name: "ensure unicorn service is not running"
        service:
          name: unicorn
          state: stopped

      when: koala_server == 'unicorn'
      become: yes

    - block:
      - name: "ensure webrick service is not running"
        service:
          name: webrick
          state: stopped

      when: koala_server == 'webrick'
      become: yes
