---

- name: "run pretix migration and other post-upgrade tasks"
  ansible.builtin.command: "/var/www/pretix/venv/bin/python -m pretix {{ item }}"
  with_items:
    - "migrate"
    - "rebuild"
    - "updatestyles"
  become: true
  become_user: "pretix"
  listen: "pretix post-upgrade"

- name: "ensure pretix is restarted if needed"
  ansible.builtin.service:
    name: "{{ item }}"
    state: "restarted"
  with_items:
    - "pretix-web.service"
    - "pretix-worker.service"
  listen: "restart pretix"

- name: "ensure maintenance mode is in desired state and reload nginx"
  ansible.builtin.service:
    name: "pretix-maintenance.service" # This service reloads nginx
    state: "started"
  listen: "pretix deploy desired nginx"
