---
- name: "install pipenv"
  pip:
    name: "pipenv"

- block:
  - name:
      "clone aas repository"
    git:
      repo: "https://github.com/svsticky/aas.git"
      dest: "/var/www/commit/aas.{{ canonical_hostname }}"
      version: "master"
    diff: false

  - name:
      "template environment file for aas"
    template:
      src: "templates/var/www/aas/.env.j2"
      dest: "/var/www/commit/aas.{{ canonical_hostname }}/.env"

  - name: "pipenv create virtual env and install aas"
    command: "pipenv install"
    args:
      chdir: "/var/www/commit/aas.{{ canonical_hostname }}"
    environment:
      PIPENV_VENV_IN_PROJECT: "1"

  become_user: commit

- name:
    "copy systemd unit"
  template:
    src: "templates/etc/systemd/system/aas.service.j2"
    dest: "/etc/systemd/system/aas.service"

- name: "copy deploy script"
  template:
    src: "templates/var/www/aas/deploy_static_sticky.sh.j2"
    dest: "/var/www/aas/deploy_static_sticky.sh"
    mode: "u+rwx"
    owner: "commit"

- name: "run aas service"
  systemd:
    unit: "aas.service"
    state: "started"
    enabled: true
    daemon-reload: true
