---
- name: "install pipenv"
  pip:
    name: "pipenv"
    umask: "0022"

- name: "permit aas user to start static-sticky deploy service"
  template:
    src: "templates/etc/sudoers.d/aas.j2"
    dest: "/etc/sudoers.d/aas"
    mode: "0440"
    validate: "/usr/sbin/visudo -cf %s"

- name: "create aas directory"
  file:
    path: "/usr/local/src/aas"
    owner: "aas"
    group: "aas"
    mode: "g+s"
    state: "directory"

- block:
  - name:
      "clone aas repository"
    git:
      repo: "https://github.com/svsticky/aas.git"
      dest: "/usr/local/src/aas"
      version: "master"
    diff: false
    register: "aas_clone"

  - name:
      "template environment file for aas"
    template:
      src: "templates/usr/local/src/aas/.env.j2"
      dest: "/usr/local/src/aas/.env"
      mode: "0600"
    notify: "restart aas"

  - name: "pipenv create virtual env and install aas"
    command: "pipenv sync"
    args:
      chdir: "/usr/local/src/aas"
    environment:
      PIPENV_VENV_IN_PROJECT: "1"
    when: "aas_clone is changed"
    notify: "restart aas"

  become_user: aas

- name:
    "copy systemd service of aas"
  template:
    src: "templates/etc/systemd/system/aas.service.j2"
    dest: "/etc/systemd/system/aas.service"
    mode: "o+r"
  notify: "restart aas"

- name: "run aas service"
  systemd:
    unit: "aas.service"
    state: "started"
    enabled: true
    daemon-reload: true
