---
- name: "install pipenv"
  pip:
    name: "pipenv"

- name: "add aas user"
  user:
    name: "aas"
    shell: "/usr/sbin/nologin"
    home: "/var/www/aas"
    system: true

- block:
  - name:
      "clone aas repository"
    git:
      repo: "https://github.com/svsticky/aas.git"
      dest: "/var/www/aas/aas.{{ canonical_hostname }}"
      version: "master"
    diff: false
    register: "new aas version detected"

  - name:
      "template environment file for aas"
    template:
      src: "templates/var/www/aas/.env.j2"
      dest: "/var/www/aas/aas.{{ canonical_hostname }}/.env"
    notify: "restart aas"

  - name: "pipenv create virtual env and install aas"
    command: "pipenv install --deploy"
    args:
      chdir: "/var/www/aas/aas.{{ canonical_hostname }}"
    environment:
      PIPENV_VENV_IN_PROJECT: "1"
    when: "new aas version detected"
    notify: "restart aas"

  become_user: aas

- name:
    "copy systemd service of aas"
  template:
    src: "templates/etc/systemd/system/aas.service.j2"
    dest: "/etc/systemd/system/aas.service"
  notify: "restart aas"

- name: "run aas service"
  systemd:
    unit: "aas.service"
    state: "started"
    enabled: true
    daemon-reload: true
