--- 
- name: "make sure dependencies are present"
  apt:
    name:
      - "python-virtualenv"
    state: "present"

- name:
    "clone aas repository"
  git:
    repo: "https://github.com/svsticky/aas.git"
    dest: "/var/www/aas/{{ canonical_hostname }}" 
    version: "master"
  diff: false

- name:
    "template environment file for aas"
  template:
    src: "templates/var/www/aas/.env.j2"
    dest: "/var/www/aas/{{ canonical_hostname }}/.env"

# TODO: do pipenv install