--- 
- name: "create aas user"
  user:
    name: "aas"
    state: "present"
    system: true
    home: "/var/www/aas"
    shell: "/bin/bash"

- name: "make sure dependencies are present"
  pip:
    name: "pipenv"
    args: "--user"

- name:
    "clone aas repository"
  git:
    repo: "https://github.com/svsticky/aas.git"
    dest: "/var/www/aas/{{ canonical_hostname }}" 
    version: "master"
  diff: false

- name:
    "template environment file for aas"
  template:
    src: "templates/var/www/aas/.env.j2"
    dest: "/var/www/aas/{{ canonical_hostname }}/.env"

- name: "pipenv create virtual env and install aas"
  command: "/var/www/aas/.local/bin/pipenv install"
  args:
    chdir: "/var/www/aas/{{ canonical_hostname }}"
  environment:
    PIPENV_VENV_IN_PROJECT: "1"

- name: "run aas service"
  systemd:
    unit: "aas.service"
    state: "running"
    enabled: true
    daemon-reload: true