--- 
- name: "make sure dependencies are present"
  apt:
    name:
      - "python-virtualenv"
    state: "present"

- name:
    "clone aas repository"
  git:
    repo: "https://github.com/svsticky/aas.git"
    # TODO: deploy directory
    dest: "" 
    version: "master"
  diff: false  

# TODO: do pipenv install