--- 
- name: "make sure dependencies are present"
  pip:
    name: "pipenv"
    args: "--user"
  become_user: "commit"

- name:
    "clone aas repository"
  git:
    repo: "https://github.com/svsticky/aas.git"
    dest: "/var/www/commit/aas.{{ canonical_hostname }}" 
    version: "master"
  diff: false

- name:
    "template environment file for aas"
  template:
    src: "templates/var/www/aas/.env.j2"
    dest: "/var/www/commit/aas.{{ canonical_hostname }}/.env"

- name: "pipenv create virtual env and install aas"
  command: "/var/www/commit/.local/bin/pipenv install"
  args:
    chdir: "/var/www/commit/aas.{{ canonical_hostname }}"
  environment:
    PIPENV_VENV_IN_PROJECT: "1"

- name:
    "copy systemd unit"
  template:
    src: "templates/etc/systemd/system/aas.service.j2"
    dest: "/etc/systemd/system/aas.service"

- name: "run aas service"
  systemd:
    unit: "aas.service"
    state: "running"
    enabled: true
    daemon-reload: true
