---

- name: "add aas user"
  user:
    name: "aas"
    shell: "/usr/sbin/nologin"
    home: "/var/www/aas"
    system: true

- name: "permit aas user to start static-sticky deploy service"
  template:
    src: "templates/etc/sudoers.d/aas.j2"
    dest: "/etc/sudoers.d/aas"
    mode: "0440"
    validate: "/usr/sbin/visudo -cf %s"

- block:
  - name:
      "clone aas repository"
    git:
      repo: "https://github.com/svsticky/aas.git"
      dest: "/var/www/aas/aas.{{ canonical_hostname }}"
      version: "master"
    diff: false
    register: "aas_clone"

  - name:
      "template environment file for aas"
    template:
      src: "templates/var/www/aas/.env.j2"
      dest: "/var/www/aas/aas.{{ canonical_hostname }}/.env"
    notify: "restart aas"

  - name: "Ensure nix environment is built"
    command: "nix-build"
    args:
      chdir: "/var/www/aas/aas.{{ canonical_hostname }}"
    when: "aas_clone is changed"
    notify: "restart aas"

  become_user: "aas"

- name:
    "copy systemd service of aas"
  template:
    src: "templates/etc/systemd/system/aas.service.j2"
    dest: "/etc/systemd/system/aas.service"
  notify: "restart aas"

- name: "run aas service"
  systemd:
    unit: "aas.service"
    state: "started"
    enabled: true
    daemon-reload: true
