---
- block:
  - name: "ensure crazy88bot has a ssh directory"
    file:
      path: "~/.ssh"
      state: "directory"

  - name: "copy deploy key (private) for user crazy88bot"
    copy:
      content: "{{ secret_deploy_key }}"
      dest: "/var/lib/crazy88bot/.ssh/id_ed25519"
      mode: "0600"

  become_user: "crazy88bot"

- name: "remove crazy88bot repo"
  file:
    dest: "/var/lib/crazy88bot/crazy88bot"
    state: "absent"

- name: "remove security override"
  file:
    path: "/etc/sudoers.d/crazy88bot"
    state: "absent"

- name: "stop and disable crazy88bot.service in production"
  systemd:
    unit: "crazy88bot.service"
    state: "stopped"
    enabled: false
    daemon-reload: true
  when: "'production' in group_names"

- name: "remove crazy88bot service file"
  file:
    path: "/etc/systemd/system/crazy88bot.service"
    state: "absent"
