---
- name: "ensure clone destination exists"
  file:
    path: "/var/lib/crazy88bot/crazy88bot"
    state: "directory"
    owner: "crazy88bot"
    group: "crazy88bot"

- block:
  - name: "ensure crazy88bot has a ssh directory"
    file:
      path: "~/.ssh"
      state: "directory"

  - name: "copy deploy key (private) for user crazy88bot"
    copy:
      content: "{{ secret_deploy_key }}"
      dest: "/var/lib/crazy88bot/.ssh/id_ed25519"
      mode: "0600"

  - name: "clone crazy88bot repo"
    git:
      repo: "git@github.com:svsticky/crazy88bot.git"
      dest: "/var/lib/crazy88bot/crazy88bot"
      key_file: "/var/lib/crazy88bot/.ssh/id_ed25519"
      version: "master"
    diff: false
    notify: "restart crazy88bot"

  - name: "ensure dependencies are installed"
    pip:
      requirements: "/var/lib/crazy88bot/crazy88bot/requirements.txt"
      virtualenv: "/var/lib/crazy88bot/crazy88bot/env"
      virtualenv_python: "python3.6"

  become_user: "crazy88bot"

- name: "copy systemd service for crazy88bot"
  template:
    src: "templates/etc/systemd/system/crazy88bot.service.j2"
    dest: "/etc/systemd/system/crazy88bot.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "restart crazy88bot"

- name: "start and enable crazy88bot.service in production"
  systemd:
    unit: "crazy88bot.service"
    state: "started"
    enabled: true
    daemon-reload: true
  when: "'production' in group_names"

- name: "allow crazy88bot to manage itself"
  template:
    src: "etc/sudoers.d/crazy88bot.j2"
    dest: "/etc/sudoers.d/crazy88bot"
    owner: "root"
    group: "root"
