---
- name: "install composer"
  apt:
    name:
      - "composer"
      - "php7.2-curl"
      - "php7.2-bcmath"
    state: "present"
  become: true

- block:
    - name: "clone digidecs repository"
      git:
        repo: "https://github.com/svsticky/digidecs.git"
        dest: "/var/www/digidecs.{{ canonical_hostname }}"
        version: "master"
      diff: false

    - name: "place config file"
      template:
        src: "templates/var/www/digidecs/config.php.j2"
        dest: "/var/www/digidecs.{{ canonical_hostname }}/config.php"
        mode: "0600"

    - name: "run composer"
      composer:
        working_dir: "/var/www/digidecs.{{ canonical_hostname }}"
        command: "install"
  become_user: "digidecs"
