---
- name: "install pipenv"
  pip:
    name: "pipenv"

- name: "ensure intro-bot user exists"
  user:
    name: "intro-bot"
    shell: "/usr/sbin/nologin"
    home: "/var/www/intro-bot"
    system: true

- block:
  - name: "ensure intro-bot has a ssh directory"
    file:
      path: "~/.ssh"
      state: "directory"

  - name: "copy deploy key for private projects on GitHub"
    copy:
      content: "{{ secret_deploy_key }}"
      dest: "/var/www/intro-bot/.ssh/id_ed25519"
      mode: "0600"
  
  - name: "clone intro-bot repository"
    git:
      repo: "git@github.com:svsticky/Digital-Intro-Bot.git"
      dest: "/var/www/intro-bot/teams-bots"
      version: "master"
    diff: false
    register: "intro_bot_clone"
    
  - name: "copy template environment file for intro-bots"
    template:
      src: "templates{{ item }}.j2"
      dest: "{{ item }}"
    diff: false
    with_items:
      - "/var/www/intro-bot/teams-bots/.env"
  
  - name: "pipenv create virtual env and install intro-bot"
    command: "pipenv sync"
    args:
      chdir: "/var/www/intro-bot/teams-bots"
    environment:
      PIPENV_VENV_IN_PROJECT: "1"
    when: "intro_bot_clone is changed"

  become_user: intro-bot

- name: "copy systemd service of intro-bots"
  template: 
    src: "templates/etc/systemd/system/intro-bot.service.j2"
    dest: "/etc/systemd/system/intro-bot.service"

- name: "run intro-bots service"
  systemd:
    unit: "intro-bot.service"
    state: "started"
    enabled: true
    daemon-reload: true