---
- name: "Download Nix install script"
  get_url:
    url: "https://releases.nixos.org/nix/nix-2.3.7/install"
    checksum: "sha256:ec6c65e46cc8f63b9cfd4df422087fa58fa9ebe823e566a885fc2a9778c721db"
    dest: "/var/tmp/install-nix"
    mode: "0755"


- name: "Run Nix installer"
  become: true
  become_user: "eindbaas"
  command: "/var/tmp/install-nix --daemon"
  args:
    creates: "/nix"

- name: "Make Nix programs available without sourcing shell stuff"
  with_items:
    - "nix"
    - "nix-build"
    - "nix-channel"
    - "nix-collect-garbage"
    - "nix-env"
    - "nix-hash"
    - "nix-instantiate"
    - "nix-prefetch-url"
    - "nix-shell"
    - "nix-store"
  file:
    src: "/nix/var/nix/profiles/default/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: "link"
  become: true
