---
- set_fact:
    oauthproxy_filename: "oauth2_proxy-v5.0.0.linux-amd64.go1.13.6"
    oauthproxy_version: "v5.0.0"
    oauthproxy_checksum: "sha256:8aa23a0635fe9ee5406e1cbef1fb86de44c660ff2269e05a04294989121c2408"

- name: "download oauth2_proxy and verify checksum"
  get_url:
    url: "https://github.com/pusher/oauth2_proxy/releases/download/{{ oauthproxy_version }}/{{ oauthproxy_filename }}.tar.gz"
    dest: "/tmp"
    mode: "u+x"
    checksum: "{{ oauthproxy_checksum }}"
  check_mode: "no"

- name: "unarchive oauth2_proxy to the right spot"
  unarchive:
    src: "/tmp/{{ oauthproxy_filename }}.tar.gz"
    remote_src: "yes"
    dest: "/usr/local/bin"
    extra_opts:
      - "--strip-components=1"

- name: "make directory"
  file:
    path: "/etc/oauth2_proxy"
    state: "directory"

- name: "copy oauth2_proxy config"
  template:
    src: "templates/etc/oauth2_proxy/config.cfg.j2"
    dest: "/etc/oauth2_proxy/config.cfg"
  notify: "restart oauth2-proxy"

- name: "install systemd service"
  template:
    src: "templates/etc/systemd/system/oauth2-proxy.service.j2"
    dest: "/etc/systemd/system/oauth2-proxy.service"
  notify: "systemctl daemon-reload"

- name: "enable and start oauth2-proxy"
  service:
    name: "oauth2-proxy"
    enabled: true
    state:  "started"

# Same thing but now for admin only oauth access

- name: "create authorized users file"
  copy:
    dest: "/etc/oauth2_proxy/authorized-users"
    content: "{{ secret_oauth2_proxy.authorized_users }}"

- name: "copy oauth2_proxy admin config"
  template:
    src: "templates/etc/oauth2_proxy/admin-config.cfg.j2"
    dest: "/etc/oauth2_proxy/admin-config.cfg"
  notify: "restart oauth2-proxy-admin"

- name: "install systemd service"
  template:
    src: "templates/etc/systemd/system/oauth2-proxy-admin.service.j2"
    dest: "/etc/systemd/system/oauth2-proxy-admin.service"
  notify: "systemctl daemon-reload"

- name: "enable and start oauth2-proxy"
  service:
    name: "oauth2-proxy-admin"
    enabled: true
    state:  "started"
