- name: "download oauth2_proxy"
  get_url:
    url: "https://github.com/svsticky/oauth2_proxy/releases/download/v2.3/oauth2_proxy"
    dest: "/usr/local/bin/oauth2_proxy"
    checksum: "sha256:82a76b75c6f5d7986c0f6a9836818d1dcd00bcf0bc2a7e36dafcbaf9e980b5df"
    mode: "0744"

- name: "make directory"
  file:
    path: "/etc/oauth2_proxy"
    state: "directory"

- name: "copy oauth2_proxy config"
  template:
    src: "templates/etc/oauth2_proxy/config.cfg.j2"
    dest: "/etc/oauth2_proxy/config.cfg"
    mode: "0600"
  notify: "restart oauth2_proxy"

- name: "install systemd service"
  template:
    src: "templates/etc/systemd/system/oauth2_proxy.service.j2"
    dest: "/etc/systemd/system/oauth2_proxy.service"
    mode: "o+r"
  notify: "systemctl daemon-reload"

- name: "enable and start oauth2-proxy"
  service:
    name: "oauth2_proxy"
    enabled: true
    state:  "started"
