---
# Contains tasks needed to set up Redis
- block:
  - name: "ensure Redis server and client are present"
    apt:
      name:
        - "redis-server"
        - "redis-tools"
      state: "present"
    tags:
        - "packages"

  - name: "create directory for onfailure override for redis service"
    file:
      path: "/etc/systemd/system/redis-server.service.d"
      state: "directory"

  - name: "copy onfailure override for redis service"
    template:
      src: "templates/etc/systemd/system/redis-server.service.d/onfailure.conf.j2"
      dest: "/etc/systemd/system/redis-server.service.d/onfailure.conf"
    notify: "systemctl daemon-reload"

  - name: "ensure Redis server is running and enabled"
    service:
        name: "redis-server"
        enabled: true
        state: "started"
    tags:
        - "service"

  - name: "place Redis config file"
    template:
      src: "templates/{{ path }}.j2"
      dest: "/{{ path }}"
      owner: "redis"
      group: "redis"
      mode: "0640"
    vars:
      path: "etc/redis/redis.conf"
    notify:
      - "restart redis"
