---
- name: "ensure shiny user exists"
  user:
    name: "shiny"
    shell: "/usr/sbin/nologin"
    home: "/var/www/shiny"
    system: true

- name: "give the shiny user read access on the koala database"
  mysql_user:
    name: "shiny"
    priv: "koala.*:SELECT"
    state: "present"
  become_user: root
  become_method: sudo

- name: "install R and other dependencies"
  apt:
    name:
      - "r-base"
      - "r-cran-shiny"
      - "r-cran-shinydashboard"
      - "r-cran-plotly"
      - "r-cran-data.table"
      - "r-cran-stringr"
      - "r-cran-dbplyr"
      - "r-cran-dplyr"
      - "r-cran-rsqlite"
    state: "present"

- name: "copy systemd service for shiny"
  template:
    src: "templates/etc/systemd/system/shiny.service.j2"
    dest: "/etc/systemd/system/shiny.service"
  notify: "restart shiny"

- block:
  - name: "ensure shiny has a ssh directory"
    file:
      path: "~/.ssh"
      state: "directory"

  - name: "copy deploy key for private projects on GitHub"
    copy:
      content: "{{ secret_deploy_key }}"
      dest: "/var/www/shiny/.ssh/id_ed25519"
      mode: "0600"

  - name: "clone shiny repository"
    git:
      repo: "git@github.com:svsticky/shiny-octopus.git"
      dest: "/var/www/shiny/stats.{{ canonical_hostname }}"
      version: "master"
    diff: false
    notify: "restart shiny"

  - name: "put config file in place"
    template:
      src: "templates/var/www/shiny/config.R"
      dest: "/var/www/shiny/stats.{{ canonical_hostname }}/config.R"
    notify: "restart shiny"

  become_user: shiny

- name: "run the shiny app"
  systemd:
    unit: "shiny.service"
    state: "started"
    enabled: true
    daemon-reload: true
