---
- name: "copy systemd service for deploying static-sticky"
  template:
    src: "templates{{ item }}.j2"
    dest: "{{ item }}"
    mode: "o+r"
  with_items:
    - "/etc/systemd/system/deploy-static-sticky.service"

- name: "copy deploy script"
  template:
    src: "templates{{ item }}.j2"
    dest: "{{ item }}"
    mode: "0744"
  with_items:
    - "/usr/local/bin/deploy-static-sticky.sh"

- name: "create webroot"
  file:
    path: "/var/www/{{ canonical_hostname }}"
    owner: "static-sticky"
    group: "www-data"
    mode: "g+s"
    state: "directory"

- name:
    "install systemd-journal-remote for accessing static-sticky's deploy logs
    remotely"
  apt:
    name: "systemd-journal-remote"
    state: "present"

- name: "start and enable systemd-journal-gatewayd"
  systemd:
    name: "systemd-journal-gatewayd"
    enabled: true
    state: "started"

- block:
  - name:
      "clone static-sticky repository"
    git:
      repo: "https://github.com/svsticky/static-sticky.git"
      dest: "/home/static-sticky/static-sticky"
      version: "{{ static_sticky_env.git_ref }}"
      depth: 1
      force: true
    diff: false
    register: "static_sticky_clone"

  - name:
      "template environment file for static-sticky"
    template:
      src: "templates{{ item }}.j2"
      dest: "{{ item }}"
      mode: "0600"
    diff: false
    with_items:
      - "/home/static-sticky/static-sticky/.env"

  - name: "clone NVM"
    git:
      repo: "https://github.com/creationix/nvm.git"
      dest: "/home/static-sticky/.nvm"
      depth: 1
    diff: false
    when: "static_sticky_clone is changed"

  - name: "install node version"
    shell: |
      . /home/static-sticky/.nvm/nvm.sh
      nvm install
    args:
      chdir: "/home/static-sticky/static-sticky"
      executable: "/bin/bash"
    when: "static_sticky_clone is changed"

  - name: "run npm install"
    shell: |
      . /home/static-sticky/.nvm/nvm.sh
      npm install
    args:
      chdir: "/home/static-sticky/static-sticky"
      executable: "/bin/bash"
    when: "static_sticky_clone is changed"

  - name: "try building website"
    block:
      - name: "build website"
        shell: |
          . /var/www/static-sticky/.nvm/nvm.sh
          npm run build
        args:
          chdir: "/home/static-sticky/static-sticky"
          executable: "/bin/bash"
    rescue:
      - name: "purge build cache to fix build failure"
        file:
          path: "/home/static-sticky/static-sticky/.cache"
          state: "absent"
      - name: "retry building website"
        shell: |
          . /var/www/static-sticky/.nvm/nvm.sh
          npm run build
        args:
          chdir: "/home/static-sticky/static-sticky"
          executable: "/bin/bash"

  # NOTE: The trailing slashes are significant!
  # Omitting it will create a `public` subdirectory and break stuff.
  # See `man rsync`, section USAGE.
  - name: "copy website contents to webroot"
    synchronize:
      src: "/home/static-sticky/static-sticky/public/"
      dest: "/var/www/{{ canonical_hostname }}/"
      delete: true
      recursive: true
      group: false
      perms: false
      times: false
    delegate_to: "{{ inventory_hostname }}"

  become_user: "static-sticky"
