---
- name: "Add user static-sticky"
  user:
    name: "static-sticky"
    shell: "/usr/sbin/nologin"
    home: "/var/www/static-sticky"
    system: true

- name: "copy systemd service for deploying static-sticky"
  template:
    src: "templates{{ item }}.j2"
    dest: "{{ item }}"
  with_items:
    - "/etc/systemd/system/deploy-static-sticky.service"

- name: "ensure polkit rules dir exists"
  file:
    path: "/etc/polkit-1/rules.d"
    state: "directory"

# a polkit rule is needed to grant aas access to the deploy-static-sticky.service
- name: "copy polkit rules"
  template:
    src: "templates{{ item }}.j2"
    dest: "{{ item }}"
  with_items:
    - "/etc/polkit-1/rules.d/00-deploy-static-sticky-service.rules"

- block:
  - name: "copy deploy script"
    template:
      src: "templates{{ item }}.j2"
      dest: "{{ item }}"
      mode: "u+rwx"
    with_items:
      - "/usr/local/bin/deploy-static-sticky.sh"

  - name:
      "clone static-sticky repository"
    git:
      repo: "https://github.com/svsticky/static-sticky.git"
      dest: "/var/www/static-sticky/static-sticky"
      version: "master"
      depth: 1
      force: true
    diff: false
    register: "new static-sticky version detected"

  - name:
      "template environment file for static-sticky"
    template:
      src: "templates{{ item }}.j2"
      dest: "{{ item }}"
    diff: false
    with_items:
      - "/var/www/static-sticky/static-sticky/.env"

  - name: "clone NVM"
    git:
      repo: "https://github.com/creationix/nvm.git"
      dest: "/var/www/static-sticky/.nvm"
      depth: 1
    diff: false
    when: "new static-sticky version detected"

  - name: "install node version"
    shell: |
      . /var/www/static-sticky/.nvm/nvm.sh
      nvm install
    args:
      chdir: "/var/www/static-sticky/static-sticky"
      executable: "/bin/bash"
    when: "new static-sticky version detected"

  - name: "run npm install"
    shell: |
      . /var/www/static-sticky/.nvm/nvm.sh
      npm install
    args:
      chdir: "/var/www/static-sticky/static-sticky"
      executable: "/bin/bash"
    when: "new static-sticky version detected"

  - name: "build website"
    shell: |
      . /var/www/static-sticky/.nvm/nvm.sh
      npm run build
    args:
      chdir: "/var/www/static-sticky/static-sticky"
      executable: "/bin/bash"

  # NOTE: The trailing slashes are significant!
  # Omitting it will create a `public` subdirectory and break stuff.
  # See `man rsync`, section USAGE.
  - name: "copy website contents to webroot"
    synchronize:
      src: "/var/www/static-sticky/static-sticky/public/"
      dest: "/var/www/static-sticky/alpha.{{ canonical_hostname }}/"
      delete: true
      archive: true

  become_user: "static-sticky"
