---
- name: "stop stickypedia service"
  systemd:
    unit: "stickypedia.service"
    state: "stopped"

- name: "remove stickypedia user"
  user:
    name: "stickypedia"
    shell: "/usr/sbin/nologin"
    home: "/var/www/stickypedia"
    system: true
    state: "absent"

- name: "remove prerequisites for gollum"
  apt:
    name:
      - "ruby"
      - "ruby-dev"
      - "libicu-dev"
    state: "absent"
  become: true

- name: "remove working directory"
  file:
    path: "/var/www/stickypedia/stickypedia.{{ canonical_hostname }}"
    state: "absent"

- name: "remove systemd service for stickypedia"
  file:
    path: "/etc/systemd/system/stickypedia.service"
    state: "absent"

- name: "remove nginx configuration for stickypedia"
  file:
    path: "/etc/nginx/sites-available/stickypedia.conf"
    state: "absent"

- name: "remove nginx config"
  file:
    path: "/etc/nginx/sites-enabled/stickypedia.{{ canonical_hostname }}.conf"
    state: "absent"

