---
- name: "create stickypedia user"
  user:
    name: "stickypedia"
    shell: "usr/sbin/nologin"
    home: "/var/www/stickypedia"
    system: true


- name: "install prerequisites for gollum"
  apt:
    name:
      - "ruby"
      - "ruby-dev"
      - "make"
      - "zlib1g-dev"
      - "libicu-dev"
      - "build-essential"
      - "git"
      - "cmake"
    state: "present"
  become: true

block:
  - name: "ensure stickypedia has a ssh directory"
    file:
      path: "~/.ssh"
      state: "directory"

  - name: "copy deploy key (private) for user stickypedia"
    copy:
      content: "{{ stickypedia.deploy_key }}"
      dest: "~/.ssh/id_ed25519"
      mode: "0600"

  - name: "clone git with Stickypedia content"
    git:
      repo: "{{ stickypedia.git_content }}"
      dest: "~/stickypedia.{{ canonical_hostname }}"
      key_file: "~/.ssh/id_ed25519"
      version: "master"
    diff: false

  - name: "copy gollum startup script"
    template:
      src: "templates/var/www/stickypedia/start-gollum.sh.j2"
      dest: "~/start-gollum.sh"
      mode: "0755"

  - name: "install gem gollum"
    gem:
      name: "gollum"
      version:  "4.1.4"
      state: "present"
    notify: "restart stickypedia"

  become_user: "stickypedia"

- name: "copy systemd service for stickypedia"
  template:
    src: "templates/etc/systemd/system/stickypedia.service.j2"
    dest: "/etc/systemd/system/stickypedia.service"
  notify: "restart stickypedia"

- name: "run stickypedia service"
  systemd:
    unit: "stickypedia.service"
    state: "started"
    enabled: true
    daemon-reload: true
