---
- name: "create stickypedia user"
  user:
    name: "stickypedia"
    shell: "/usr/sbin/nologin"
    home: "/var/www/stickypedia"
    system: true

- name: "install prerequisites for gollum"
  apt:
    name:
      - "ruby"
      - "ruby-dev"
      - "make"
      - "zlib1g-dev"
      - "libicu-dev"
      - "build-essential"
      - "git"
      - "cmake"
    state: "present"
  become: true

- name: "make sure gem is at a version compatible with gollum"
  shell: "gem update --system 3.0.6"

- block:
    - name: "create working directory"
      file:
        path: "/var/www/stickypedia/stickypedia.{{ canonical_hostname }}"
        state: "directory"
        mode: "0700"

    - name: "copy gollum startup script"
      template:
        src: "templates/var/www/stickypedia/start-gollum.sh.j2"
        dest: "~/start-gollum.sh"
        mode: "0770"

    - name: "install gem gollum"
      gem:
        name: "gollum"
        version: "4.1.4"
        state: "present"

  become_user: "stickypedia"

- name: "copy systemd service for stickypedia"
  template:
    src: "templates/etc/systemd/system/stickypedia.service.j2"
    dest: "/etc/systemd/system/stickypedia.service"
  notify: "restart stickypedia"

- name: "copy nginx configuration for stickypedia"
  template:
    src: "templates/etc/nginx/sites-available/stickypedia.conf.j2"
    dest: "/etc/nginx/sites-available/stickypedia.conf"

- name: "run stickypedia service"
  systemd:
    unit: "stickypedia.service"
    state: "started"
    enabled: true
    daemon-reload: true
