---
- name: "create stickypedia user"
  user:
    name: "stickypedia"
    shell: "usr/sbin/nologin"
    home: "/var/www/stickypedia"
    system: true

block:
  - name: "clone git with Stickypedia content"
    git:
      repo: {{ stickypedia.git_content }}
      dest: "/var/www/stickypedia/stickypedia.{{ canonical_hostname }}"
      version: "master"
    diff: false

  - name: "install prerequisites for gollum"
    apt:
      name:
        - "ruby"
        - "ruby-dev"
        - "make"
        - "zlib1g-dev"
        - "libicu-dev"
        - "build-essential"
        - "git"
        - "cmake"
      state: "present"
    become: true

  - name: "install gem gollum"
    gem:
      name: gollum
      state: latest
    notify: "restart stickypedia"

  become_user: stickypedia

- name: "copy systemd service for stickypedia"
  template:
    src: "templates/etc/systemd/system/stickypedia.service.j2"
    dest: "/etc/systemd/system/golum.service"

- name: "run stickypedia service"
  systemd:
    unit: "stickypedia.service"
    state: "started"
    enabled: true
    daemon-reload: true
