---
- name: "restart mongoose"
  ansible.builtin.service:
    name: "mongoose"
    state: "restarted"

- name: "run migrations"
  become_user: "mongoose"
  become: true
  ansible.builtin.command: "uv run --env-file .env manage.py migrate"
  args:
    chdir: "/var/www/mongoose/undead-mongoose"
  listen: "run migrations"
  notify: "restart mongoose"
