---
# Contains application-agnostic database tasks
- name: "add apt key for postgresql"
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: "present"
    id: "B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8"

- name: "add postgresql apt repository"
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg main"

- name: "ensure postgresql is installed and manageable"
  apt:
    name:
      - "postgresql-13"
      - "python3-psycopg2"

- block:
  - name: "ensure koala user exists"
    postgresql_user:
      name: "koala"

  - name: "ensure koala database exists"
    postgresql_db:
      name: "koala"
      owner: "koala"

  - name: "ensure koala user exists"
    postgresql_user:
      db: "koala"
      name: "koala"
      priv: "ALL"
      role_attr_flags: "CREATEDB,LOGIN"

  - name: "ensure dbeaver koala user exists"
    postgresql_user:
      db: "koala"
      name: "koala_manual"
      password: "{{ secret_koala_manual.password }}"
      priv: "CONNECT"
      role_attr_flags: "NOSUPERUSER"

  - name: "ensure dbeaver koala user has the right privs"
    postgresql_privs:
      db: "koala"
      role: "koala_manual"
      objs: "ALL_IN_SCHEMA"
      privs: "SELECT"

  become_user: "postgres"
