---
# Contains application-agnostic database tasks
- name: "add apt key for postgresql"
  ansible.builtin.apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: "present"
    id: "B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8"

- name: "add postgresql apt repository"
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg main"

- name: "ensure postgresql is installed and manageable"
  ansible.builtin.apt:
    name:
      - "postgresql-14" # Installs postgres 14 if not installed yet
      - "python3-psycopg2"

- name: "Explicitly specify peer auth as default over local communication"
  become_user: "postgres"
  become: true
  community.postgresql.postgresql_pg_hba:
    dest: "{{ postgres.pg_hba_path }}"
    backup: true
    backup_file: "{{ postgres.pg_hba_path }}.old"

    # TYPE  DATABASE USER ADDR METHOD
    # local all      all       peer
    contype: "local"
    databases: "all"
    users: "all"
    method: "peer"
  notify: "restart postgres" # Apply changes

- name: "set up tavern databases"
  become_user: "postgres"
  become: true
  block:

  - name: "ensure tavern user exists"
    community.postgresql.postgresql_user:
      name: "tavern"
      password: "{{ secret_tavern.postgres_password }}"

  - name: "ensure tavern database exists"
    community.postgresql.postgresql_db:
      name: "tavern"
      owner: "tavern"

  - name: "ensure tavern user exists"
    community.postgresql.postgresql_user:
      db: "tavern"
      name: "tavern"
      role_attr_flags: "CREATEDB,LOGIN"

  - name: "ensure tavern user has the right privs"
    community.postgresql.postgresql_privs:
      db: "tavern"
      role: "tavern"
      objs: "ALL_IN_SCHEMA"
      privs: "ALL"


- name: "set up keycloak databases"
  become_user: "postgres"
  become: true
  block:

  - name: "ensure keycloak user exists"
    community.postgresql.postgresql_user:
      name: "keycloak"
      password: "{{ secret_keycloak.db_password }}"

  - name: "ensure keycloak database exists"
    community.postgresql.postgresql_db:
      name: "keycloak"
      owner: "keycloak"

  - name: "ensure keycloak user exists"
    community.postgresql.postgresql_user:
      db: "keycloak"
      name: "keycloak"
      role_attr_flags: "CREATEDB,LOGIN"

  - name: "ensure keycloak user has the right privs"
    community.postgresql.postgresql_privs:
      db: "keycloak"
      role: "keycloak"
      objs: "ALL_IN_SCHEMA"
      privs: "ALL"
