---
# Contains application-agnostic database tasks
- name: "add apt key for postgresql"
  ansible.builtin.apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: "present"
    id: "B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8"

- name: "add postgresql apt repository"
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg main"

- name: "ensure postgresql is installed and manageable"
  ansible.builtin.apt:
    name:
      - "postgresql-13"
      - "python3-psycopg2"


- name: "Explicitly specify peer auth as default over local communication"
  become_user: "postgres"
  become: true
  community.postgresql.postgresql_pg_hba:
    dest: "{{ postgres.pg_hba_path }}"
    backup: true
    backup_file: "{{ postgres.pg_hba_path }}.old"

    # TYPE  DATABASE USER ADDR METHOD
    # local all      all       peer
    contype: 'local'
    databases: 'all'
    users: 'all'
    method: 'peer'


- name: "set up koala databases"
  become_user: "postgres"
  become: true
  block:

  - name: "ensure koala user exists"
    community.postgresql.postgresql_user:
      name: "koala"

  - name: "ensure koala database exists"
    community.postgresql.postgresql_db:
      name: "koala"
      owner: "koala"

  - name: "ensure koala user exists"
    community.postgresql.postgresql_user:
      db: "koala"
      name: "koala"
      role_attr_flags: "CREATEDB,LOGIN"

  - name: "ensure koala user has the right privs"
    community.postgresql.postgresql_privs:
      db: "koala"
      role: "koala"
      objs: "ALL_IN_SCHEMA"
      privs: "ALL"

  - name: "ensure dbeaver koala user exists"
    community.postgresql.postgresql_user:
      db: "koala"
      name: "koala_manual"
      password: "{{ secret_koala_manual.password }}"
      role_attr_flags: "NOSUPERUSER"

  - name: "ensure dbeaver koala user has the right privs"
    community.postgresql.postgresql_privs:
      db: "koala"
      role: "koala_manual"
      objs: "ALL_IN_SCHEMA"
      privs: "SELECT"

  - name: "ensure dbeaver koala user has the right privs"
    community.postgresql.postgresql_privs:
      db: "koala"
      role: "koala_manual"
      type: "database"
      privs: "CONNECT"
