---
# Contains application-agnostic database tasks
- name: ensure mariadb is installed and managable
  apt:
      name: "{{item}}"
      state: present
  with_items:
      - mariadb-server
      - python-mysqldb
  tags:
      - database
      - packages

- name: ensure database is enabled and running
  service:
      name: mysql
      enabled: yes
      state: started
  tags:
      - service
      - database

- name: generate and set database root password if not set
  mysql_user:
     name: root
     password: "{{ lookup('password', 'credentials/mysql/root length=64 chars=hexdigits') }}"
  tags:
   - database

- name: ensure /root/.my.cnf is present and correct
  template:
    src: templates/root-.my.cnf
    dest: ~/.my.cnf
  tags:
    - database
