---
- block:

  - name: ensure nginx is installed
    apt:
      name: nginx
      state: present

  - name: place koala's nginx configuration
    template:
      src: templates/nginx-koala.svsticky.nl
      dest: /etc/nginx/sites-available/koala.svsticky.nl
      owner: root
      group: root

  - name: enable koala's nginx config
    file:
      src: /etc/nginx/sites-available/koala.svsticky.nl
      dest: /etc/nginx/sites-enabled/koala.svsticky.nl
      state: link
      owner: root
      group: root

  when: koala_server_method == 'production'
  become: yes
