---
- name: "Create user for fallacious-rooster"
  ansible.builtin.user:
    name: fallacious-rooster
    home: "/var/www/fallacious-rooster"
    shell: "/usr/sbin/nologin"
    system: true
    state: "present"

- name: "Create fallacious-rooster frontend directory"
  ansible.builtin.file:
    name: "/var/www/fallacious-rooster/frontend"
    owner: "fallacious-rooster"
    group: "fallacious-rooster"
    mode: "2775"
    state: "directory"

- name: "Create fallacious-rooster server directory"
  ansible.builtin.file:
    name: "/var/www/fallacious-rooster/server"
    owner: "fallacious-rooster"
    group: "fallacious-rooster"
    mode: "2775"
    state: "directory"

- name: "install dependencies"
  ansible.builtin.apt:
    name:
      - "python3-dotenv-cli"
    state: "present"

- name: "Download and extract fallacious-rooster frontend"
  ansible.builtin.unarchive:
    src: https://github.com/svsticky/fallacious-rooster/releases/download/{{ fallacious_rooster.git_tag }}/frontend.tar.gz
    dest: "/var/www/fallacious-rooster/frontend"
    remote_src: true
    owner: "fallacious-rooster"
    group: "fallacious-rooster"
    mode: "775"
    extra_opts:
    - "--strip-components=1"

- name: "Download and extract fallacious-rooster server"
  ansible.builtin.get_url:
    url: https://github.com/svsticky/fallacious-rooster/releases/download/{{ fallacious_rooster.git_tag }}/server-x86_64-unknown-linux-musl
    dest: "/var/www/fallacious-rooster/server"
    owner: "fallacious-rooster"
    group: "fallacious-rooster"
    mode: "775"
  notify: "restart fallacious-rooster"

- name: "Copy nginx configuration"
  ansible.builtin.template:
    src: "fallacious-rooster.conf.j2"
    dest: "/etc/nginx/sites-enabled/fallacious-rooster.{{ canonical_hostname }}.conf"
  notify: "reload nginx"

- name: "Template environment file for fallacious-rooster"
  ansible.builtin.template:
    src: "env.j2"
    dest: "/var/www/fallacious-rooster/server/.env"
  diff: false
  notify: "restart fallacious-rooster"

- name: "Template config file for fallacious-rooster"
  ansible.builtin.template:
    src: "fallacious-rooster.json.j2"
    dest: "/var/www/fallacious-rooster/server/config.json"
  diff: false
  notify: "restart fallacious-rooster"

- name: "template systemd service file for fallacious-rooster"
  ansible.builtin.template:
    src: "fallacious-rooster.service.j2"
    dest: "/etc/systemd/system/fallacious-rooster.service"
  notify: "restart fallacious-rooster"

- name: "run fallacious-rooster-roosterma service"
  ansible.builtin.systemd:
    unit: "fallacious-rooster.service"
    state: "started"
    enabled: true
    daemon-reload: true
