---
- name: "create site root Fancy Index & theme dir"
  ansible.builtin.file:
    path: "/var/www/files.{{ canonical_hostname }}"
    owner: "www-data"
    group: "adm"
    mode: "2775"
    state: "directory"

- name: "create site root Fancy Index & theme dir"
  ansible.builtin.file:
    path: "/var/www/files.{{ canonical_hostname }}/theme"
    owner: "www-data"
    group: "www-data"
    state: "directory"

# The theming generation can be found at https://github.com/svsticky/fancy-index
- name: "copy Fancy Index theme"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/www/files.{{ canonical_hostname }}/theme/{{ item }}"
    owner: "www-data"
    group: "www-data"
  loop:
    - "footer.html"
    - "header.html"
    - "style.css"
    - "fa-brands-400.ttf"

- name: "copy NGiNX site config Fancy Index"
  ansible.builtin.template:
    src: "files.conf.j2"
    dest: "/etc/nginx/sites-available/files.{{ canonical_hostname }}.conf"
  notify: "reload nginx"

- name: "enable NGiNX site config Fancy Index"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ filename }}"
    path: "/etc/nginx/sites-enabled/{{ filename }}"
    state: "link"
  vars:
    filename: "files.{{ canonical_hostname }}.conf"
  notify: "reload nginx"
