---
- name: "check if koala is running"
  ansible.builtin.systemd:
    name: "koala.service"
    state: "started"
  check_mode: true
  register: "koala_running"
  listen: "restart koala"

- name: "restart koala service"
  ansible.builtin.service:
    name: "koala"
    state: "restarted"
  when: "koala_running is not changed"
  listen: "restart koala"

- name: "restart sidekiq service"
  ansible.builtin.service:
    name: "sidekiq"
    state: "restarted"
  listen: "restart sidekiq"

- name: "clone koala to /var/www/koala.{{ canonical_hostname }}"
  become_user: "koala"
  become: true
  ansible.builtin.git:
    repo: "git@github.com:svsticky/constipated-koala.git"
    dest: "/var/www/koala.{{ canonical_hostname }}"
    version: "{{ koala_env.git_ref }}"
  diff: false
  listen: "clone koala"
  notify: "restart sidekiq"

- name: "create marker file to trigger migration"
  become_user: "koala"
  become: true
  ansible.builtin.file:
    path: "/home/koala/.KOALA_MIGRATION_PENDING"
    state: "touch"
    owner: "koala"
    group: "koala"
  listen: "trigger migration"
