---
- name: "check if koala is running"
  ansible.builtin.systemd:
    name: "koala.service"
    state: "started"
  check_mode: true
  register: "koala_running"
  listen: "restart koala"

- name: "restart koala service"
  ansible.builtin.service:
    name: "koala"
    state: "restarted"
  when: "koala_running is not changed"
  listen: "restart koala"

- name: "restart sidekiq service"
  ansible.builtin.service:
    name: "sidekiq"
    state: "restarted"
  listen: "restart sidekiq"
