---
- name: "copy docker containers logrotate config"
  ansible.builtin.template:
    src: "docker-containers.conf.j2"
    dest: "/etc/logrotate.d/docker-containers"
    owner: "root"
    mode: "0644"
