---
- name: "restart oauth2-proxy"
  ansible.builtin.systemd:
    name: "oauth2-proxy"
    state: "restarted"
    daemon_reload: true
  listen: "restart oauth2-proxy"

- name: "restart oauth2-proxy (admin)"
  ansible.builtin.systemd:
    name: "oauth2-proxy-admin"
    state: "restarted"
    daemon_reload: true
  listen: "restart oauth2-proxy-admin"
