---
- name: "restart oauth2-proxy"
  service:
    name: "oauth2-proxy"
    state: "restarted"
  listen: "restart oauth2-proxy"

- name: "restart oauth2-proxy (admin)"
  service:
    name: "oauth2-proxy-admin"
    state: "restarted"
  listen: "restart oauth2-proxy-admin"
