---
- name: "install nginx, openssl and fancyindex"
  apt:
    name:
      - "nginx"
      - "openssl"
      - "libnginx-mod-http-fancyindex"
    state: "present"

- name: "create directories for onfailure override for nginx"
  file:
    path: "/etc/systemd/system/nginx.service.d"
    state: "directory"

- name: "copy onfailure override for nginx"
  template:
    src: "onfailure.conf.j2"
    dest: "/etc/systemd/system/nginx.service.d/onfailure.conf"
  notify: "systemctl daemon-reload"

- name: "create nginx includes directory"
  file:
    path: "/etc/nginx/includes"
    state: "directory"

- name: "copy nginx include files"
  template:
    src: "includes/{{ item }}.j2"
    dest: "/etc/nginx/includes/{{ item }}"
  loop:
    - "block-cert-validation-path.conf"
    - "execut-referer-tracking.conf"
    - "php-parameters.conf"
    - "security-headers.conf"
  notify: "reload nginx"

- name: "copy general configuration file for nginx"
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  notify: "reload nginx"

- name: "ensure stock nginx configuration is not present"
  file:
    path: "/etc/nginx/{{ item }}"
    state: "absent"
  loop:
    - "sites-available/default"
    - "sites-enabled/default"
  notify: "reload nginx"

- name: "copy dhparams"
  copy:
    src: "dhparams.pem"
    dest: "/etc/nginx/dhparams.pem"
  notify: "reload nginx"

- name: "copy default nginx configuration"
  template:
    src: "sites-available/default.conf.j2"
    dest: "/etc/nginx/sites-available/default.conf"
  notify: "reload nginx"

- name: "enable default nginx config"
  file:
    src: "/etc/nginx/sites-available/default.conf"
    path: "/etc/nginx/sites-enabled/default"
    state: "link"
  notify: "reload nginx"

# This enables the nginx service, and starts it if necessary. Certbot depends on
# this.
- name: "enable and start nginx"
  service:
    name: "nginx"
    enabled: true
    state: "started"

- name: "Delete default html directory"
  file:
    path: "/var/www/html"
    state: "absent"
