---
- name: "disable git safe directory feature for sodi folder" # noqa command-instead-of-module
  ansible.builtin.command: "git config --global --add safe.directory /var/www/sodi.{{ canonical_hostname }}"

- name: "clone sodi website from git"
  ansible.builtin.git:
    repo: "git@github.com:svsticky/sodi.nl.git"
    dest: "/var/www/sodi.{{ canonical_hostname }}"
    version: "master"
  diff: false

- name: "set permissions group on sodi files"
  ansible.builtin.file:
    path: "/var/www/sodi.{{ canonical_hostname }}"
    owner: "www-data"
    group: "www-data"
    recurse: true
    state: "directory"
