---
- name: "clone sodi website from git"
  git:
    repo: "git@github.com:svsticky/sodi.nl.git"
    dest: "/var/www/sodi.{{ canonical_hostname }}"
    version: "master"
  diff: false

- name: "set permissions group on sodi files"
  file:
    path: "/var/www/sodi.{{ canonical_hostname }}"
    owner: "www-data"
    group: "www-data"
    recurse: true
    state: "directory"
