---
- name: "install pipenv"
  ansible.builtin.pip:
    name: "pipenv"

- name: "ensure crazy88bot user exists"
  ansible.builtin.user:
    name: "crazy88bot"
    shell: "/usr/sbin/nologin"
    home: "{{ crazy88bot_config.home }}"
    system: true
    create_home: false

- name: "Create home directory"
  ansible.builtin.file:
    path: "{{ crazy88bot_config.home }}"
    owner: "crazy88bot"
    group: "crazy88bot"
    mode: "2775"
    state: "directory"


- name: "set up crazy88bot"
  become_user: "crazy88bot"
  become: true
  block:

  - name: "ensure intro-bot has a ssh directory"
    ansible.builtin.file:
      path: "~/.ssh"
      state: "directory"

  - name: "copy deploy key for private projects on GitHub"
    ansible.builtin.copy:
      content: "{{ secret_deploy_key }}"
      dest: "/var/www/crazy88bot/.ssh/id_ed25519"
      mode: "0600"

  - name: "clone crazy88bot repository"
    ansible.builtin.git:
      repo: "git@github.com:svsticky/crazy88bot.git"
      dest: "/var/www/crazy88bot/crazy88bot"
      version: "master"
    diff: false
    notify: # Only call when there was a git update (or fresh clone)
      - "pipenv create virtual env and install crazy88bot"
      - "restart crazy88bot"

- name: "flush handlers before starting crazy88bot"
  ansible.builtin.meta: flush_handlers

- name: "copy systemd service of intro-bots"
  ansible.builtin.template:
    src: "crazy88bot.service.j2"
    dest: "/etc/systemd/system/crazy88bot.service"

- name: "run crazy88bot service"
  ansible.builtin.systemd:
    unit: "crazy88bot.service"
    state: "started"
    enabled: true
    daemon-reload: true
