---
# FIXME docker exposed ports bypass ufw firefwall, which we use.
# See https://docs.docker.com/network/packet-filtering-firewalls/#docker-and-ufw

- name: "Install Docker"
  block:

  - name: "Add Docker apt repository"
    ansible.builtin.deb822_repository: # See https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
      name: "docker"
      types: "deb"
      uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
      suites: "{{ ansible_distribution_release }}"
      components: "stable"
      architectures: "amd64"
      signed_by: "https://download.docker.com/linux/ubuntu/gpg"

  - name: "Install Docker packages"
    ansible.builtin.package:
      name:
        - "docker-ce={{ docker_engine_version }}"
        - "docker-ce-cli={{ docker_engine_version }}"
        - "containerd.io"
        - "docker-buildx-plugin"
      state: "present"
      update_cache: true

  - name: "Ensure Docker is started and enabled at boot"
    ansible.builtin.service:
      name: "docker"
      state: "started"
      enabled: true

- name: "Install Docker Compose"
  ansible.builtin.package:
    name: "docker-compose-plugin"
    state: "present"

- name: "Ensure admin users are added to the docker group"
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "docker"
    append: true
  with_items: "{{ users }}"
  when: "item.admin"
  loop_control:
    label: "Adding '{{ item.name }}' to the docker group"
