---
- name: "check if koala is running"
  command: "systemctl is-active koala"
  register: "koala_running"
  listen: "restart koala"

- name: "restart koala service"
  service:
    name: "koala"
    state: "restarted"
  when: koala_running.rc == 0
  listen: "restart koala"

- name: "restart fail2ban"
  service:
    name: "fail2ban"
    state: "restarted"

- name: "reload nginx"
  service:
    name: "nginx"
    state: "reloaded"

- name: "systemctl daemon-reload"
  command: "systemctl daemon-reload"

- name: "issue reboot command"
  shell: "sleep 2 && /sbin/reboot"
  async: 60
  poll: 0
  ignore_errors: true
  listen: "reboot server"

- name: "wait for server to finish rebooting"
  wait_for_connection:
    delay: 20
  listen: "reboot server"
