---

# This task is used for websites which use the default nginx config, and need
# its webroot to be created.
- name: "create directories for regular websites"
  ansible.builtin.file:
    path:
      "/var/www/{% if item.user is defined %}{{ item.user }}/{% endif %}{{
      item.name }}"
    owner: "www-data"
    group: "{{ item.user | default(omit) }}"
    mode: "2775"
    state: "directory"
  with_items: "{{ websites }}"
  when:
    # List is evaluated as logical AND
    - item.state == "present"
    - "item.custom_config is undefined or not item.custom_config"
  loop_control:
    label: "{{ item.name }}"

- name: "copy nginx configurations for regular websites"
  ansible.builtin.template:
    src: "website.conf.j2"
    dest: "/etc/nginx/sites-available/{{ item.name }}.conf"
  with_items: "{{ websites }}"
  when:
    # List is evaluated as logical AND
    - item.state == "present"
    - "item.custom_config is undefined or not item.custom_config"
  notify: "reload nginx"
  loop_control:
    label: "{{ item.name }}"

- name: "enable regular nginx configurations"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ item.name }}.conf"
    path: "/etc/nginx/sites-enabled/{{ item.name }}.conf"
    state: "link"
  with_items: "{{ websites }}"
  when:
    # List is evaluated as logical AND
    - item.state == "present"
    - "item.custom_config is undefined or not item.custom_config"
  notify: "reload nginx"
  loop_control:
    label: "{{ item.name }}"

- name: "copy custom nginx configurations"
  ansible.builtin.template:
    src: "{{ item.src }}.conf.j2"
    dest: "/etc/nginx/sites-available/{{ item.dest }}.conf"
  with_items:
    - src: "dgdarc"
      dest: "dgdarc.{{ canonical_hostname }}"
    - src: "savadaba"
      dest: "savadaba.{{ canonical_hostname }}"
    - src: "wintersport"
      dest: "wintersport.{{ canonical_hostname }}"
    - src: "intro-cs"
      dest: "intro-cs.{{ canonical_hostname }}"
  notify: "reload nginx"
  loop_control:
    label: "{{ item.dest }}"

- name: "enable custom nginx configurations"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ item }}.conf"
    path: "/etc/nginx/sites-enabled/{{ item }}.conf"
    state: "link"
  with_items:
    - "dgdarc.{{ canonical_hostname }}"
    - "savadaba.{{ canonical_hostname }}"
    - "wintersport.{{ canonical_hostname }}"
    - "intro-cs.{{ canonical_hostname }}"
  notify: "reload nginx"

- name: "delete nginx configuration (sites-enabled) of absent websites"
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/{{ item.name }}.conf"
    state: "absent"
  with_items: "{{ websites }}"
  when: item.state == "absent"
  notify: "reload nginx"

- name: "delete nginx configuration (sites-available) of absent websites"
  ansible.builtin.file:
    path: "/etc/nginx/sites-available/{{ item.name }}.conf"
    state: "absent"
  with_items: "{{ websites }}"
  when: item.state == "absent"
  notify: "reload nginx"
