---
- name: "copy Nix install script"
  copy:
    src: "install"
    dest: "/var/tmp/install-nix"
    mode: "0755"

- name: "Run Nix installer"
  become: true
  become_user: "eindbaas"
  command: "/var/tmp/install-nix --daemon"
  args:
    creates: "/nix"

- name: "Make Nix programs available without sourcing shell stuff"
  with_items:
    - "nix"
    - "nix-build"
    - "nix-channel"
    - "nix-collect-garbage"
    - "nix-env"
    - "nix-hash"
    - "nix-instantiate"
    - "nix-prefetch-url"
    - "nix-shell"
    - "nix-store"
  file:
    src: "/nix/var/nix/profiles/default/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: "link"
  become: true

- name: "install cachix" # noqa 305
  shell: "nix-env -iA cachix -f https://cachix.org/api/v1/install"

- name: "Make cachix available without sourcing shell stuff"
  file:
    src: "/nix/var/nix/profiles/default/bin/cachix"
    dest: "/usr/local/bin/cachix"
    state: "link"
  become: true
