---

- name: "add aas user"
  user:
    name: "aas"
    shell: "/usr/sbin/nologin"
    home: "/var/www/aas"
    system: true

- name: "permit aas user to start static-sticky deploy service"
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers.d/aas"
    mode: "0440"
    validate: "/usr/sbin/visudo -cf %s"

- name: "add cachix cache"
  command: "cachix use svsticky-aas"

- name: "fetch the aas binaries"
  command:
    cmd: "nix-store --realize --add-root /nix/var/nix/gcroots/aas-env {{ secret_aas.nix_pin }}"

- name: "ensure config directory exists"
  file:
    path: "/etc/aas"
    state: "directory"

- name: "create environment file"
  template:
    src: ".env.j2"
    dest: "/etc/aas/.env"
    owner: "root"
    mode: "0600"
  notify: "restart aas"

- name: "copy nginx configuration"
  template:
    src: "aas.conf.j2"
    dest: "/etc/nginx/sites-available/aas.{{ canonical_hostname }}.conf"
  notify: "reload nginx"

- name: "enable nginx configuration"
  file:
    src: "/etc/nginx/sites-available/aas.{{ canonical_hostname }}.conf"
    path: "/etc/nginx/sites-enabled/aas.{{ canonical_hostname }}.conf"
    state: "link"
  notify: "reload nginx"

- name:
    "copy systemd service of aas"
  template:
    src: "aas.service.j2"
    dest: "/etc/systemd/system/aas.service"
  notify: "restart aas"

- name: "run aas service"
  systemd:
    unit: "aas.service"
    state: "started"
    enabled: true
    daemon-reload: true
