---

- name: "install certbot and digital ocean plugin"
  apt:
    name:
      - "certbot"
      - "python3-certbot-dns-digitalocean"
    state: "latest"

# This directory will be used to validate all websites that need a certificate
- name: "create acme-challenges directory"
  file:
    path: "/var/www/acme-challenges"
    state: "directory"
    owner: "root"
    group: "www-data"
    # The 2xxx octal means the group setuid bit is set, meaning all files that
    # get created in this directory will have the group `www-data`.
    mode: "2750"

- name: "create folders for certbot renewal override"
  file:
    path: "/etc/systemd/system/{{ item }}"
    state: "directory"
  with_items:
    - "certbot.service.d"
    - "certbot.timer.d"

- name: "place onfailure override"
  template:
    src: "onfailure.conf.j2"
    dest: "/etc/systemd/system/certbot.service.d/onfailure.conf"
  notify: "systemctl daemon-reload"

- name: "override parameters of certbot's renewal service+timer"
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - "certbot.service.d/override.conf"
    - "certbot.timer.d/override.conf"
  notify: "systemctl daemon-reload"

- name: "place digital ocean credentials file"
  template:
    src: "certbot-creds.ini.j2"
    dest: "/etc/letsencrypt/certbot-creds.ini"
    mode: "600"

# To make sure nginx is reloaded if needed
- meta: "flush_handlers"

- name: "request certificates"
  # --non-interactive makes sure command never waits for user input
  # --keep-until-expiring makes sure cert only gets renewed when cert is
  # actually close to expiring
  # --expand enables adding more SAN's to the same cert lineage later on
  # --webroot sets domain validation method
  # --domain adds main hostname of a website as CN and SAN, and all alternative
  # hostnames as SAN's
  # --deploy-hook reloads nginx after a successful issuance, and adds this in
  # the renewal configuration of the certificate
  command: >-
    certbot certonly
    --non-interactive
    --agree-tos
    --email "domreg@svsticky.nl"
    --keep-until-expiring
    --cert-name {{ canonical_hostname }}
    --dns-digitalocean
    --dns-digitalocean-credentials /etc/letsencrypt/certbot-creds.ini
    --domain "*.{{ canonical_hostname }}"
    --domain "{{ canonical_hostname }}"
    --deploy-hook "systemctl reload nginx"
  register: "certbot_output"
  changed_when: "'no action taken' not in certbot_output.stdout"

- name: "ensure certbot timer is started"
  service:
    name: "certbot.timer"
    enabled: true
    state: "started"
