---

# Mark migration as started
# Ensures migration critical processes will be continued upon abortion
- name: "Create migration marker"
  become_user: "committeeclash"
  become: true
  ansible.builtin.file:
    path: "{{ committeeclash_home_dir }}/.MIGRATION_PENDING"
    state: "touch"
    owner: "committeeclash"
    group: "committeeclash"
  listen: "trigger committeeclash migration"


- name: "Ensure committeeclash is offline"
  community.docker.docker_compose_v2:
    project_src: "{{ committeeclash_project_source }}"
    files: [ "docker-compose.prod.yml" ]

    state: "absent"
  listen: "backup committeeclash"
  # TODO create a maintenance mode?

- name: "Make backup of committeeclash database"
  become_user: "root"
  become: true
  ansible.builtin.systemd:
    name: "backup-postgres.service"
    state: "started" # Given the systemd service type, this awaits untill finished
  listen: "backup committeeclash"
